// Code generated by Fern. DO NOT EDIT.

package accounts

import (
	context "context"
	levelfour "github.com/LevelFourAI/levelfour-go"
	core "github.com/LevelFourAI/levelfour-go/core"
	internal "github.com/LevelFourAI/levelfour-go/internal"
	option "github.com/LevelFourAI/levelfour-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) CreateIntegration(
	ctx context.Context,
	request *levelfour.CreateIntegrationRequest,
	opts ...option.RequestOption,
) (*levelfour.CreateIntegrationResponse, error) {
	response, err := c.WithRawResponse.CreateIntegration(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetIntegrationStatus(
	ctx context.Context,
	integrationID string,
	opts ...option.RequestOption,
) (*levelfour.IntegrationStatusResponse, error) {
	response, err := c.WithRawResponse.GetIntegrationStatus(
		ctx,
		integrationID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CompleteGithubIntegration(
	ctx context.Context,
	integrationID string,
	request *levelfour.GithubCompleteRequest,
	opts ...option.RequestOption,
) (*levelfour.IntegrationStatusResponse, error) {
	response, err := c.WithRawResponse.CompleteGithubIntegration(
		ctx,
		integrationID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CompleteGitlabIntegration(
	ctx context.Context,
	integrationID string,
	request *levelfour.GitlabCompleteRequest,
	opts ...option.RequestOption,
) (*levelfour.GitlabConnectResponse, error) {
	response, err := c.WithRawResponse.CompleteGitlabIntegration(
		ctx,
		integrationID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CompleteJiraIntegration(
	ctx context.Context,
	integrationID string,
	request *levelfour.JiraCompleteRequest,
	opts ...option.RequestOption,
) (*levelfour.JiraCompleteResponse, error) {
	response, err := c.WithRawResponse.CompleteJiraIntegration(
		ctx,
		integrationID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListGithubInstallations(
	ctx context.Context,
	opts ...option.RequestOption,
) (*levelfour.SrcAccountsSchemasGithubInstallationsResponse, error) {
	response, err := c.WithRawResponse.ListGithubInstallations(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListGitlabConnections(
	ctx context.Context,
	opts ...option.RequestOption,
) (*levelfour.GitlabConnectionsResponse, error) {
	response, err := c.WithRawResponse.ListGitlabConnections(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DisconnectGitlabConnection(
	ctx context.Context,
	connectionID string,
	opts ...option.RequestOption,
) (*levelfour.GitlabDisconnectResponse, error) {
	response, err := c.WithRawResponse.DisconnectGitlabConnection(
		ctx,
		connectionID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListJiraConnections(
	ctx context.Context,
	opts ...option.RequestOption,
) (*levelfour.JiraConnectionsResponse, error) {
	response, err := c.WithRawResponse.ListJiraConnections(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) DisconnectJiraConnection(
	ctx context.Context,
	connectionID string,
	opts ...option.RequestOption,
) (*levelfour.JiraDisconnectResponse, error) {
	response, err := c.WithRawResponse.DisconnectJiraConnection(
		ctx,
		connectionID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListConnectedAccounts(
	ctx context.Context,
	request *levelfour.ListConnectedAccountsAPIV1AccountsGetRequest,
	opts ...option.RequestOption,
) (*levelfour.ConnectedAccountsResponse, error) {
	response, err := c.WithRawResponse.ListConnectedAccounts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListConnections(
	ctx context.Context,
	opts ...option.RequestOption,
) (*levelfour.ConnectionsResponse, error) {
	response, err := c.WithRawResponse.ListConnections(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListCustomerModules(
	ctx context.Context,
	opts ...option.RequestOption,
) (*levelfour.CustomerModulesResponse, error) {
	response, err := c.WithRawResponse.ListCustomerModules(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
