// Code generated by Fern. DO NOT EDIT.

package levelfour

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/LevelFourAI/levelfour-go/internal"
	big "math/big"
	time "time"
)

var (
	githubCompleteRequestFieldInstallationID = big.NewInt(1 << 0)
	githubCompleteRequestFieldSetupAction    = big.NewInt(1 << 1)
)

type GithubCompleteRequest struct {
	// GitHub App installation ID returned by the Setup URL callback
	InstallationID int `json:"installation_id" url:"-"`
	// GitHub Setup URL action. install on first install, update when repos/permissions changed.
	SetupAction GithubCompleteRequestSetupAction `json:"setup_action" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GithubCompleteRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetInstallationID sets the InstallationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubCompleteRequest) SetInstallationID(installationID int) {
	g.InstallationID = installationID
	g.require(githubCompleteRequestFieldInstallationID)
}

// SetSetupAction sets the SetupAction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubCompleteRequest) SetSetupAction(setupAction GithubCompleteRequestSetupAction) {
	g.SetupAction = setupAction
	g.require(githubCompleteRequestFieldSetupAction)
}

func (g *GithubCompleteRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubCompleteRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GithubCompleteRequest(body)
	return nil
}

func (g *GithubCompleteRequest) MarshalJSON() ([]byte, error) {
	type embed GithubCompleteRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createIntegrationRequestFieldProvider   = big.NewInt(1 << 0)
	createIntegrationRequestFieldMode       = big.NewInt(1 << 1)
	createIntegrationRequestFieldTargetOuID = big.NewInt(1 << 2)
)

type CreateIntegrationRequest struct {
	// Cloud provider identifier
	Provider *CreateIntegrationRequestProvider `json:"provider,omitempty" url:"-"`
	// Onboarding mode. AWS: single|organization. GitHub: github_app.
	Mode CreateIntegrationRequestMode `json:"mode" url:"-"`
	// AWS Organizations root ID (r-...) or organizational unit ID (ou-...-...). Required when provider='aws' and mode='organization'; ignored otherwise.
	TargetOuID *string `json:"target_ou_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateIntegrationRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateIntegrationRequest) SetProvider(provider *CreateIntegrationRequestProvider) {
	c.Provider = provider
	c.require(createIntegrationRequestFieldProvider)
}

// SetMode sets the Mode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateIntegrationRequest) SetMode(mode CreateIntegrationRequestMode) {
	c.Mode = mode
	c.require(createIntegrationRequestFieldMode)
}

// SetTargetOuID sets the TargetOuID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateIntegrationRequest) SetTargetOuID(targetOuID *string) {
	c.TargetOuID = targetOuID
	c.require(createIntegrationRequestFieldTargetOuID)
}

func (c *CreateIntegrationRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateIntegrationRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateIntegrationRequest(body)
	return nil
}

func (c *CreateIntegrationRequest) MarshalJSON() ([]byte, error) {
	type embed CreateIntegrationRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	listConnectedAccountsAPIV1AccountsGetRequestFieldPage     = big.NewInt(1 << 0)
	listConnectedAccountsAPIV1AccountsGetRequestFieldPageSize = big.NewInt(1 << 1)
)

type ListConnectedAccountsAPIV1AccountsGetRequest struct {
	// Page number (1-indexed)
	Page *int `json:"-" url:"page,omitempty"`
	// Items per page (max 200)
	PageSize *int `json:"-" url:"page_size,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListConnectedAccountsAPIV1AccountsGetRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConnectedAccountsAPIV1AccountsGetRequest) SetPage(page *int) {
	l.Page = page
	l.require(listConnectedAccountsAPIV1AccountsGetRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListConnectedAccountsAPIV1AccountsGetRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listConnectedAccountsAPIV1AccountsGetRequestFieldPageSize)
}

var (
	connectedAccountFieldAccountID           = big.NewInt(1 << 0)
	connectedAccountFieldAccountName         = big.NewInt(1 << 1)
	connectedAccountFieldRoleArn             = big.NewInt(1 << 2)
	connectedAccountFieldRegionName          = big.NewInt(1 << 3)
	connectedAccountFieldStatus              = big.NewInt(1 << 4)
	connectedAccountFieldIsManagementAccount = big.NewInt(1 << 5)
	connectedAccountFieldOrganizationID      = big.NewInt(1 << 6)
	connectedAccountFieldConnectedAt         = big.NewInt(1 << 7)
)

type ConnectedAccount struct {
	// 12-digit AWS account identifier
	AccountID   string  `json:"account_id" url:"account_id"`
	AccountName *string `json:"account_name,omitempty" url:"account_name,omitempty"`
	// Deterministic ARN of LevelFourCrossAccountRole in the customer's account
	RoleArn             string                 `json:"role_arn" url:"role_arn"`
	RegionName          *string                `json:"region_name,omitempty" url:"region_name,omitempty"`
	Status              ConnectedAccountStatus `json:"status" url:"status"`
	IsManagementAccount *bool                  `json:"is_management_account,omitempty" url:"is_management_account,omitempty"`
	OrganizationID      *string                `json:"organization_id,omitempty" url:"organization_id,omitempty"`
	ConnectedAt         *time.Time             `json:"connected_at,omitempty" url:"connected_at,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConnectedAccount) GetAccountID() string {
	if c == nil {
		return ""
	}
	return c.AccountID
}

func (c *ConnectedAccount) GetAccountName() *string {
	if c == nil {
		return nil
	}
	return c.AccountName
}

func (c *ConnectedAccount) GetRoleArn() string {
	if c == nil {
		return ""
	}
	return c.RoleArn
}

func (c *ConnectedAccount) GetRegionName() *string {
	if c == nil {
		return nil
	}
	return c.RegionName
}

func (c *ConnectedAccount) GetStatus() ConnectedAccountStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *ConnectedAccount) GetIsManagementAccount() *bool {
	if c == nil {
		return nil
	}
	return c.IsManagementAccount
}

func (c *ConnectedAccount) GetOrganizationID() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationID
}

func (c *ConnectedAccount) GetConnectedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ConnectedAt
}

func (c *ConnectedAccount) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConnectedAccount) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectedAccount) SetAccountID(accountID string) {
	c.AccountID = accountID
	c.require(connectedAccountFieldAccountID)
}

// SetAccountName sets the AccountName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectedAccount) SetAccountName(accountName *string) {
	c.AccountName = accountName
	c.require(connectedAccountFieldAccountName)
}

// SetRoleArn sets the RoleArn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectedAccount) SetRoleArn(roleArn string) {
	c.RoleArn = roleArn
	c.require(connectedAccountFieldRoleArn)
}

// SetRegionName sets the RegionName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectedAccount) SetRegionName(regionName *string) {
	c.RegionName = regionName
	c.require(connectedAccountFieldRegionName)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectedAccount) SetStatus(status ConnectedAccountStatus) {
	c.Status = status
	c.require(connectedAccountFieldStatus)
}

// SetIsManagementAccount sets the IsManagementAccount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectedAccount) SetIsManagementAccount(isManagementAccount *bool) {
	c.IsManagementAccount = isManagementAccount
	c.require(connectedAccountFieldIsManagementAccount)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectedAccount) SetOrganizationID(organizationID *string) {
	c.OrganizationID = organizationID
	c.require(connectedAccountFieldOrganizationID)
}

// SetConnectedAt sets the ConnectedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectedAccount) SetConnectedAt(connectedAt *time.Time) {
	c.ConnectedAt = connectedAt
	c.require(connectedAccountFieldConnectedAt)
}

func (c *ConnectedAccount) UnmarshalJSON(data []byte) error {
	type embed ConnectedAccount
	var unmarshaler = struct {
		embed
		ConnectedAt *internal.DateTime `json:"connected_at,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = ConnectedAccount(unmarshaler.embed)
	c.ConnectedAt = unmarshaler.ConnectedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConnectedAccount) MarshalJSON() ([]byte, error) {
	type embed ConnectedAccount
	var marshaler = struct {
		embed
		ConnectedAt *internal.DateTime `json:"connected_at,omitempty"`
	}{
		embed:       embed(*c),
		ConnectedAt: internal.NewOptionalDateTime(c.ConnectedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConnectedAccount) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type ConnectedAccountStatus string

const (
	ConnectedAccountStatusPendingRole ConnectedAccountStatus = "pending_role"
	ConnectedAccountStatusConnected   ConnectedAccountStatus = "connected"
	ConnectedAccountStatusError       ConnectedAccountStatus = "error"
	ConnectedAccountStatusRevoked     ConnectedAccountStatus = "revoked"
)

func NewConnectedAccountStatusFromString(s string) (ConnectedAccountStatus, error) {
	switch s {
	case "pending_role":
		return ConnectedAccountStatusPendingRole, nil
	case "connected":
		return ConnectedAccountStatusConnected, nil
	case "error":
		return ConnectedAccountStatusError, nil
	case "revoked":
		return ConnectedAccountStatusRevoked, nil
	}
	var t ConnectedAccountStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c ConnectedAccountStatus) Ptr() *ConnectedAccountStatus {
	return &c
}

var (
	connectedAccountsDataFieldItems      = big.NewInt(1 << 0)
	connectedAccountsDataFieldPagination = big.NewInt(1 << 1)
)

type ConnectedAccountsData struct {
	Items      []*ConnectedAccount `json:"items" url:"items"`
	Pagination *PaginationMeta     `json:"pagination" url:"pagination"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConnectedAccountsData) GetItems() []*ConnectedAccount {
	if c == nil {
		return nil
	}
	return c.Items
}

func (c *ConnectedAccountsData) GetPagination() *PaginationMeta {
	if c == nil {
		return nil
	}
	return c.Pagination
}

func (c *ConnectedAccountsData) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConnectedAccountsData) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectedAccountsData) SetItems(items []*ConnectedAccount) {
	c.Items = items
	c.require(connectedAccountsDataFieldItems)
}

// SetPagination sets the Pagination field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectedAccountsData) SetPagination(pagination *PaginationMeta) {
	c.Pagination = pagination
	c.require(connectedAccountsDataFieldPagination)
}

func (c *ConnectedAccountsData) UnmarshalJSON(data []byte) error {
	type unmarshaler ConnectedAccountsData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConnectedAccountsData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConnectedAccountsData) MarshalJSON() ([]byte, error) {
	type embed ConnectedAccountsData
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConnectedAccountsData) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	connectedAccountsResponseFieldSuccess   = big.NewInt(1 << 0)
	connectedAccountsResponseFieldTimestamp = big.NewInt(1 << 1)
	connectedAccountsResponseFieldData      = big.NewInt(1 << 2)
)

type ConnectedAccountsResponse struct {
	Success   *bool                  `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time             `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *ConnectedAccountsData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConnectedAccountsResponse) GetSuccess() *bool {
	if c == nil {
		return nil
	}
	return c.Success
}

func (c *ConnectedAccountsResponse) GetTimestamp() *time.Time {
	if c == nil {
		return nil
	}
	return c.Timestamp
}

func (c *ConnectedAccountsResponse) GetData() *ConnectedAccountsData {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *ConnectedAccountsResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConnectedAccountsResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectedAccountsResponse) SetSuccess(success *bool) {
	c.Success = success
	c.require(connectedAccountsResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectedAccountsResponse) SetTimestamp(timestamp *time.Time) {
	c.Timestamp = timestamp
	c.require(connectedAccountsResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConnectedAccountsResponse) SetData(data *ConnectedAccountsData) {
	c.Data = data
	c.require(connectedAccountsResponseFieldData)
}

func (c *ConnectedAccountsResponse) UnmarshalJSON(data []byte) error {
	type embed ConnectedAccountsResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = ConnectedAccountsResponse(unmarshaler.embed)
	c.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConnectedAccountsResponse) MarshalJSON() ([]byte, error) {
	type embed ConnectedAccountsResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*c),
		Timestamp: internal.NewOptionalDateTime(c.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConnectedAccountsResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createIntegrationDataFieldIntegrationID    = big.NewInt(1 << 0)
	createIntegrationDataFieldLaunchStackURL   = big.NewInt(1 << 1)
	createIntegrationDataFieldLaunchInstallURL = big.NewInt(1 << 2)
	createIntegrationDataFieldExpiresAt        = big.NewInt(1 << 3)
)

type CreateIntegrationData struct {
	// UUID minted per click; correlates pingback/callback to dashboard session
	IntegrationID string `json:"integration_id" url:"integration_id"`
	// AWS Console quickcreate URL with pre-filled CFN parameters. Populated when provider='aws'.
	LaunchStackURL *string `json:"launch_stack_url,omitempty" url:"launch_stack_url,omitempty"`
	// GitHub App install URL with state parameter. Populated when provider='github'.
	LaunchInstallURL *string `json:"launch_install_url,omitempty" url:"launch_install_url,omitempty"`
	// When the integration session expires (no pingback/callback received)
	ExpiresAt time.Time `json:"expires_at" url:"expires_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateIntegrationData) GetIntegrationID() string {
	if c == nil {
		return ""
	}
	return c.IntegrationID
}

func (c *CreateIntegrationData) GetLaunchStackURL() *string {
	if c == nil {
		return nil
	}
	return c.LaunchStackURL
}

func (c *CreateIntegrationData) GetLaunchInstallURL() *string {
	if c == nil {
		return nil
	}
	return c.LaunchInstallURL
}

func (c *CreateIntegrationData) GetExpiresAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.ExpiresAt
}

func (c *CreateIntegrationData) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateIntegrationData) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetIntegrationID sets the IntegrationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateIntegrationData) SetIntegrationID(integrationID string) {
	c.IntegrationID = integrationID
	c.require(createIntegrationDataFieldIntegrationID)
}

// SetLaunchStackURL sets the LaunchStackURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateIntegrationData) SetLaunchStackURL(launchStackURL *string) {
	c.LaunchStackURL = launchStackURL
	c.require(createIntegrationDataFieldLaunchStackURL)
}

// SetLaunchInstallURL sets the LaunchInstallURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateIntegrationData) SetLaunchInstallURL(launchInstallURL *string) {
	c.LaunchInstallURL = launchInstallURL
	c.require(createIntegrationDataFieldLaunchInstallURL)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateIntegrationData) SetExpiresAt(expiresAt time.Time) {
	c.ExpiresAt = expiresAt
	c.require(createIntegrationDataFieldExpiresAt)
}

func (c *CreateIntegrationData) UnmarshalJSON(data []byte) error {
	type embed CreateIntegrationData
	var unmarshaler = struct {
		embed
		ExpiresAt *internal.DateTime `json:"expires_at"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreateIntegrationData(unmarshaler.embed)
	c.ExpiresAt = unmarshaler.ExpiresAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateIntegrationData) MarshalJSON() ([]byte, error) {
	type embed CreateIntegrationData
	var marshaler = struct {
		embed
		ExpiresAt *internal.DateTime `json:"expires_at"`
	}{
		embed:     embed(*c),
		ExpiresAt: internal.NewDateTime(c.ExpiresAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateIntegrationData) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createIntegrationResponseFieldSuccess   = big.NewInt(1 << 0)
	createIntegrationResponseFieldTimestamp = big.NewInt(1 << 1)
	createIntegrationResponseFieldData      = big.NewInt(1 << 2)
)

type CreateIntegrationResponse struct {
	Success   *bool                  `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time             `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *CreateIntegrationData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateIntegrationResponse) GetSuccess() *bool {
	if c == nil {
		return nil
	}
	return c.Success
}

func (c *CreateIntegrationResponse) GetTimestamp() *time.Time {
	if c == nil {
		return nil
	}
	return c.Timestamp
}

func (c *CreateIntegrationResponse) GetData() *CreateIntegrationData {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateIntegrationResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateIntegrationResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateIntegrationResponse) SetSuccess(success *bool) {
	c.Success = success
	c.require(createIntegrationResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateIntegrationResponse) SetTimestamp(timestamp *time.Time) {
	c.Timestamp = timestamp
	c.require(createIntegrationResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateIntegrationResponse) SetData(data *CreateIntegrationData) {
	c.Data = data
	c.require(createIntegrationResponseFieldData)
}

func (c *CreateIntegrationResponse) UnmarshalJSON(data []byte) error {
	type embed CreateIntegrationResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreateIntegrationResponse(unmarshaler.embed)
	c.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateIntegrationResponse) MarshalJSON() ([]byte, error) {
	type embed CreateIntegrationResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*c),
		Timestamp: internal.NewOptionalDateTime(c.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateIntegrationResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	customerModuleFieldModuleID  = big.NewInt(1 << 0)
	customerModuleFieldStatus    = big.NewInt(1 << 1)
	customerModuleFieldPlanTier  = big.NewInt(1 << 2)
	customerModuleFieldStartedAt = big.NewInt(1 << 3)
	customerModuleFieldExpiresAt = big.NewInt(1 << 4)
	customerModuleFieldConfig    = big.NewInt(1 << 5)
)

type CustomerModule struct {
	// Module identifier (e.g. 'github_bot', 'cloud_savings')
	ModuleID string `json:"module_id" url:"module_id"`
	// Current module state for this tenant
	Status CustomerModuleStatus `json:"status" url:"status"`
	// Plan tier label, free text (e.g. 'paid', 'free')
	PlanTier  *string    `json:"plan_tier,omitempty" url:"plan_tier,omitempty"`
	StartedAt *time.Time `json:"started_at,omitempty" url:"started_at,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty" url:"expires_at,omitempty"`
	// Module-specific config (e.g. trial caps, allowed recommendation ids, enabled providers)
	Config map[string]any `json:"config,omitempty" url:"config,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomerModule) GetModuleID() string {
	if c == nil {
		return ""
	}
	return c.ModuleID
}

func (c *CustomerModule) GetStatus() CustomerModuleStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CustomerModule) GetPlanTier() *string {
	if c == nil {
		return nil
	}
	return c.PlanTier
}

func (c *CustomerModule) GetStartedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartedAt
}

func (c *CustomerModule) GetExpiresAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ExpiresAt
}

func (c *CustomerModule) GetConfig() map[string]any {
	if c == nil {
		return nil
	}
	return c.Config
}

func (c *CustomerModule) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CustomerModule) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetModuleID sets the ModuleID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerModule) SetModuleID(moduleID string) {
	c.ModuleID = moduleID
	c.require(customerModuleFieldModuleID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerModule) SetStatus(status CustomerModuleStatus) {
	c.Status = status
	c.require(customerModuleFieldStatus)
}

// SetPlanTier sets the PlanTier field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerModule) SetPlanTier(planTier *string) {
	c.PlanTier = planTier
	c.require(customerModuleFieldPlanTier)
}

// SetStartedAt sets the StartedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerModule) SetStartedAt(startedAt *time.Time) {
	c.StartedAt = startedAt
	c.require(customerModuleFieldStartedAt)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerModule) SetExpiresAt(expiresAt *time.Time) {
	c.ExpiresAt = expiresAt
	c.require(customerModuleFieldExpiresAt)
}

// SetConfig sets the Config field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerModule) SetConfig(config map[string]any) {
	c.Config = config
	c.require(customerModuleFieldConfig)
}

func (c *CustomerModule) UnmarshalJSON(data []byte) error {
	type embed CustomerModule
	var unmarshaler = struct {
		embed
		StartedAt *internal.DateTime `json:"started_at,omitempty"`
		ExpiresAt *internal.DateTime `json:"expires_at,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CustomerModule(unmarshaler.embed)
	c.StartedAt = unmarshaler.StartedAt.TimePtr()
	c.ExpiresAt = unmarshaler.ExpiresAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerModule) MarshalJSON() ([]byte, error) {
	type embed CustomerModule
	var marshaler = struct {
		embed
		StartedAt *internal.DateTime `json:"started_at,omitempty"`
		ExpiresAt *internal.DateTime `json:"expires_at,omitempty"`
	}{
		embed:     embed(*c),
		StartedAt: internal.NewOptionalDateTime(c.StartedAt),
		ExpiresAt: internal.NewOptionalDateTime(c.ExpiresAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CustomerModule) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Current module state for this tenant
type CustomerModuleStatus string

const (
	CustomerModuleStatusInactive CustomerModuleStatus = "inactive"
	CustomerModuleStatusTrial    CustomerModuleStatus = "trial"
	CustomerModuleStatusActive   CustomerModuleStatus = "active"
	CustomerModuleStatusPastDue  CustomerModuleStatus = "past_due"
	CustomerModuleStatusRevoked  CustomerModuleStatus = "revoked"
	CustomerModuleStatusBeta     CustomerModuleStatus = "beta"
)

func NewCustomerModuleStatusFromString(s string) (CustomerModuleStatus, error) {
	switch s {
	case "inactive":
		return CustomerModuleStatusInactive, nil
	case "trial":
		return CustomerModuleStatusTrial, nil
	case "active":
		return CustomerModuleStatusActive, nil
	case "past_due":
		return CustomerModuleStatusPastDue, nil
	case "revoked":
		return CustomerModuleStatusRevoked, nil
	case "beta":
		return CustomerModuleStatusBeta, nil
	}
	var t CustomerModuleStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CustomerModuleStatus) Ptr() *CustomerModuleStatus {
	return &c
}

var (
	customerModulesDataFieldItems = big.NewInt(1 << 0)
)

type CustomerModulesData struct {
	Items []*CustomerModule `json:"items" url:"items"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomerModulesData) GetItems() []*CustomerModule {
	if c == nil {
		return nil
	}
	return c.Items
}

func (c *CustomerModulesData) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CustomerModulesData) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerModulesData) SetItems(items []*CustomerModule) {
	c.Items = items
	c.require(customerModulesDataFieldItems)
}

func (c *CustomerModulesData) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomerModulesData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomerModulesData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerModulesData) MarshalJSON() ([]byte, error) {
	type embed CustomerModulesData
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CustomerModulesData) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	customerModulesResponseFieldSuccess   = big.NewInt(1 << 0)
	customerModulesResponseFieldTimestamp = big.NewInt(1 << 1)
	customerModulesResponseFieldData      = big.NewInt(1 << 2)
)

type CustomerModulesResponse struct {
	Success   *bool                `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time           `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *CustomerModulesData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomerModulesResponse) GetSuccess() *bool {
	if c == nil {
		return nil
	}
	return c.Success
}

func (c *CustomerModulesResponse) GetTimestamp() *time.Time {
	if c == nil {
		return nil
	}
	return c.Timestamp
}

func (c *CustomerModulesResponse) GetData() *CustomerModulesData {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CustomerModulesResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CustomerModulesResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerModulesResponse) SetSuccess(success *bool) {
	c.Success = success
	c.require(customerModulesResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerModulesResponse) SetTimestamp(timestamp *time.Time) {
	c.Timestamp = timestamp
	c.require(customerModulesResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomerModulesResponse) SetData(data *CustomerModulesData) {
	c.Data = data
	c.require(customerModulesResponseFieldData)
}

func (c *CustomerModulesResponse) UnmarshalJSON(data []byte) error {
	type embed CustomerModulesResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CustomerModulesResponse(unmarshaler.embed)
	c.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomerModulesResponse) MarshalJSON() ([]byte, error) {
	type embed CustomerModulesResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*c),
		Timestamp: internal.NewOptionalDateTime(c.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CustomerModulesResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	githubInstallationFieldInstallationID = big.NewInt(1 << 0)
	githubInstallationFieldAccountLogin   = big.NewInt(1 << 1)
	githubInstallationFieldRepos          = big.NewInt(1 << 2)
	githubInstallationFieldConnectedAt    = big.NewInt(1 << 3)
)

type GithubInstallation struct {
	// GitHub App installation ID
	InstallationID int `json:"installation_id" url:"installation_id"`
	// GitHub organization or user login the app is installed on
	AccountLogin string `json:"account_login" url:"account_login"`
	// Full names (owner/name) of repos in the installation
	Repos       []string   `json:"repos,omitempty" url:"repos,omitempty"`
	ConnectedAt *time.Time `json:"connected_at,omitempty" url:"connected_at,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubInstallation) GetInstallationID() int {
	if g == nil {
		return 0
	}
	return g.InstallationID
}

func (g *GithubInstallation) GetAccountLogin() string {
	if g == nil {
		return ""
	}
	return g.AccountLogin
}

func (g *GithubInstallation) GetRepos() []string {
	if g == nil {
		return nil
	}
	return g.Repos
}

func (g *GithubInstallation) GetConnectedAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.ConnectedAt
}

func (g *GithubInstallation) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubInstallation) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetInstallationID sets the InstallationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubInstallation) SetInstallationID(installationID int) {
	g.InstallationID = installationID
	g.require(githubInstallationFieldInstallationID)
}

// SetAccountLogin sets the AccountLogin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubInstallation) SetAccountLogin(accountLogin string) {
	g.AccountLogin = accountLogin
	g.require(githubInstallationFieldAccountLogin)
}

// SetRepos sets the Repos field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubInstallation) SetRepos(repos []string) {
	g.Repos = repos
	g.require(githubInstallationFieldRepos)
}

// SetConnectedAt sets the ConnectedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubInstallation) SetConnectedAt(connectedAt *time.Time) {
	g.ConnectedAt = connectedAt
	g.require(githubInstallationFieldConnectedAt)
}

func (g *GithubInstallation) UnmarshalJSON(data []byte) error {
	type embed GithubInstallation
	var unmarshaler = struct {
		embed
		ConnectedAt *internal.DateTime `json:"connected_at,omitempty"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GithubInstallation(unmarshaler.embed)
	g.ConnectedAt = unmarshaler.ConnectedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubInstallation) MarshalJSON() ([]byte, error) {
	type embed GithubInstallation
	var marshaler = struct {
		embed
		ConnectedAt *internal.DateTime `json:"connected_at,omitempty"`
	}{
		embed:       embed(*g),
		ConnectedAt: internal.NewOptionalDateTime(g.ConnectedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubInstallation) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubInstallationsDataFieldItems = big.NewInt(1 << 0)
)

type GithubInstallationsData struct {
	Items []*GithubInstallation `json:"items" url:"items"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubInstallationsData) GetItems() []*GithubInstallation {
	if g == nil {
		return nil
	}
	return g.Items
}

func (g *GithubInstallationsData) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubInstallationsData) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubInstallationsData) SetItems(items []*GithubInstallation) {
	g.Items = items
	g.require(githubInstallationsDataFieldItems)
}

func (g *GithubInstallationsData) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubInstallationsData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubInstallationsData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubInstallationsData) MarshalJSON() ([]byte, error) {
	type embed GithubInstallationsData
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubInstallationsData) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	githubInstallationsResponseFieldSuccess   = big.NewInt(1 << 0)
	githubInstallationsResponseFieldTimestamp = big.NewInt(1 << 1)
	githubInstallationsResponseFieldData      = big.NewInt(1 << 2)
)

type GithubInstallationsResponse struct {
	Success   *bool                    `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time               `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *GithubInstallationsData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubInstallationsResponse) GetSuccess() *bool {
	if g == nil {
		return nil
	}
	return g.Success
}

func (g *GithubInstallationsResponse) GetTimestamp() *time.Time {
	if g == nil {
		return nil
	}
	return g.Timestamp
}

func (g *GithubInstallationsResponse) GetData() *GithubInstallationsData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GithubInstallationsResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubInstallationsResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubInstallationsResponse) SetSuccess(success *bool) {
	g.Success = success
	g.require(githubInstallationsResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubInstallationsResponse) SetTimestamp(timestamp *time.Time) {
	g.Timestamp = timestamp
	g.require(githubInstallationsResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubInstallationsResponse) SetData(data *GithubInstallationsData) {
	g.Data = data
	g.require(githubInstallationsResponseFieldData)
}

func (g *GithubInstallationsResponse) UnmarshalJSON(data []byte) error {
	type embed GithubInstallationsResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GithubInstallationsResponse(unmarshaler.embed)
	g.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubInstallationsResponse) MarshalJSON() ([]byte, error) {
	type embed GithubInstallationsResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*g),
		Timestamp: internal.NewOptionalDateTime(g.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubInstallationsResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	integrationStatusDataFieldIntegrationID        = big.NewInt(1 << 0)
	integrationStatusDataFieldProvider             = big.NewInt(1 << 1)
	integrationStatusDataFieldMode                 = big.NewInt(1 << 2)
	integrationStatusDataFieldStatus               = big.NewInt(1 << 3)
	integrationStatusDataFieldDiscoveredAccountIDs = big.NewInt(1 << 4)
	integrationStatusDataFieldErrorMessage         = big.NewInt(1 << 5)
	integrationStatusDataFieldPollingHintMs        = big.NewInt(1 << 6)
	integrationStatusDataFieldExpiresAt            = big.NewInt(1 << 7)
)

type IntegrationStatusData struct {
	IntegrationID string                        `json:"integration_id" url:"integration_id"`
	Provider      IntegrationStatusDataProvider `json:"provider" url:"provider"`
	Mode          IntegrationStatusDataMode     `json:"mode" url:"mode"`
	Status        IntegrationStatusDataStatus   `json:"status" url:"status"`
	// Populated once status='connected'. AWS: one entry per onboarded account. GitHub: one entry per installed GitHub org login.
	DiscoveredAccountIDs []string `json:"discovered_account_ids,omitempty" url:"discovered_account_ids,omitempty"`
	// Populated when status='failed'
	ErrorMessage *string `json:"error_message,omitempty" url:"error_message,omitempty"`
	// How long the dashboard should wait before polling again; 0 when terminal
	PollingHintMs int       `json:"polling_hint_ms" url:"polling_hint_ms"`
	ExpiresAt     time.Time `json:"expires_at" url:"expires_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntegrationStatusData) GetIntegrationID() string {
	if i == nil {
		return ""
	}
	return i.IntegrationID
}

func (i *IntegrationStatusData) GetProvider() IntegrationStatusDataProvider {
	if i == nil {
		return ""
	}
	return i.Provider
}

func (i *IntegrationStatusData) GetMode() IntegrationStatusDataMode {
	if i == nil {
		return ""
	}
	return i.Mode
}

func (i *IntegrationStatusData) GetStatus() IntegrationStatusDataStatus {
	if i == nil {
		return ""
	}
	return i.Status
}

func (i *IntegrationStatusData) GetDiscoveredAccountIDs() []string {
	if i == nil {
		return nil
	}
	return i.DiscoveredAccountIDs
}

func (i *IntegrationStatusData) GetErrorMessage() *string {
	if i == nil {
		return nil
	}
	return i.ErrorMessage
}

func (i *IntegrationStatusData) GetPollingHintMs() int {
	if i == nil {
		return 0
	}
	return i.PollingHintMs
}

func (i *IntegrationStatusData) GetExpiresAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.ExpiresAt
}

func (i *IntegrationStatusData) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *IntegrationStatusData) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetIntegrationID sets the IntegrationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntegrationStatusData) SetIntegrationID(integrationID string) {
	i.IntegrationID = integrationID
	i.require(integrationStatusDataFieldIntegrationID)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntegrationStatusData) SetProvider(provider IntegrationStatusDataProvider) {
	i.Provider = provider
	i.require(integrationStatusDataFieldProvider)
}

// SetMode sets the Mode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntegrationStatusData) SetMode(mode IntegrationStatusDataMode) {
	i.Mode = mode
	i.require(integrationStatusDataFieldMode)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntegrationStatusData) SetStatus(status IntegrationStatusDataStatus) {
	i.Status = status
	i.require(integrationStatusDataFieldStatus)
}

// SetDiscoveredAccountIDs sets the DiscoveredAccountIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntegrationStatusData) SetDiscoveredAccountIDs(discoveredAccountIDs []string) {
	i.DiscoveredAccountIDs = discoveredAccountIDs
	i.require(integrationStatusDataFieldDiscoveredAccountIDs)
}

// SetErrorMessage sets the ErrorMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntegrationStatusData) SetErrorMessage(errorMessage *string) {
	i.ErrorMessage = errorMessage
	i.require(integrationStatusDataFieldErrorMessage)
}

// SetPollingHintMs sets the PollingHintMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntegrationStatusData) SetPollingHintMs(pollingHintMs int) {
	i.PollingHintMs = pollingHintMs
	i.require(integrationStatusDataFieldPollingHintMs)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntegrationStatusData) SetExpiresAt(expiresAt time.Time) {
	i.ExpiresAt = expiresAt
	i.require(integrationStatusDataFieldExpiresAt)
}

func (i *IntegrationStatusData) UnmarshalJSON(data []byte) error {
	type embed IntegrationStatusData
	var unmarshaler = struct {
		embed
		ExpiresAt *internal.DateTime `json:"expires_at"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = IntegrationStatusData(unmarshaler.embed)
	i.ExpiresAt = unmarshaler.ExpiresAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntegrationStatusData) MarshalJSON() ([]byte, error) {
	type embed IntegrationStatusData
	var marshaler = struct {
		embed
		ExpiresAt *internal.DateTime `json:"expires_at"`
	}{
		embed:     embed(*i),
		ExpiresAt: internal.NewDateTime(i.ExpiresAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IntegrationStatusData) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type IntegrationStatusDataMode string

const (
	IntegrationStatusDataModeSingle       IntegrationStatusDataMode = "single"
	IntegrationStatusDataModeOrganization IntegrationStatusDataMode = "organization"
	IntegrationStatusDataModeGithubApp    IntegrationStatusDataMode = "github_app"
)

func NewIntegrationStatusDataModeFromString(s string) (IntegrationStatusDataMode, error) {
	switch s {
	case "single":
		return IntegrationStatusDataModeSingle, nil
	case "organization":
		return IntegrationStatusDataModeOrganization, nil
	case "github_app":
		return IntegrationStatusDataModeGithubApp, nil
	}
	var t IntegrationStatusDataMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i IntegrationStatusDataMode) Ptr() *IntegrationStatusDataMode {
	return &i
}

type IntegrationStatusDataProvider string

const (
	IntegrationStatusDataProviderAws    IntegrationStatusDataProvider = "aws"
	IntegrationStatusDataProviderGithub IntegrationStatusDataProvider = "github"
)

func NewIntegrationStatusDataProviderFromString(s string) (IntegrationStatusDataProvider, error) {
	switch s {
	case "aws":
		return IntegrationStatusDataProviderAws, nil
	case "github":
		return IntegrationStatusDataProviderGithub, nil
	}
	var t IntegrationStatusDataProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i IntegrationStatusDataProvider) Ptr() *IntegrationStatusDataProvider {
	return &i
}

type IntegrationStatusDataStatus string

const (
	IntegrationStatusDataStatusPending   IntegrationStatusDataStatus = "pending"
	IntegrationStatusDataStatusVerifying IntegrationStatusDataStatus = "verifying"
	IntegrationStatusDataStatusConnected IntegrationStatusDataStatus = "connected"
	IntegrationStatusDataStatusFailed    IntegrationStatusDataStatus = "failed"
	IntegrationStatusDataStatusExpired   IntegrationStatusDataStatus = "expired"
)

func NewIntegrationStatusDataStatusFromString(s string) (IntegrationStatusDataStatus, error) {
	switch s {
	case "pending":
		return IntegrationStatusDataStatusPending, nil
	case "verifying":
		return IntegrationStatusDataStatusVerifying, nil
	case "connected":
		return IntegrationStatusDataStatusConnected, nil
	case "failed":
		return IntegrationStatusDataStatusFailed, nil
	case "expired":
		return IntegrationStatusDataStatusExpired, nil
	}
	var t IntegrationStatusDataStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i IntegrationStatusDataStatus) Ptr() *IntegrationStatusDataStatus {
	return &i
}

var (
	integrationStatusResponseFieldSuccess   = big.NewInt(1 << 0)
	integrationStatusResponseFieldTimestamp = big.NewInt(1 << 1)
	integrationStatusResponseFieldData      = big.NewInt(1 << 2)
)

type IntegrationStatusResponse struct {
	Success   *bool                  `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time             `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *IntegrationStatusData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntegrationStatusResponse) GetSuccess() *bool {
	if i == nil {
		return nil
	}
	return i.Success
}

func (i *IntegrationStatusResponse) GetTimestamp() *time.Time {
	if i == nil {
		return nil
	}
	return i.Timestamp
}

func (i *IntegrationStatusResponse) GetData() *IntegrationStatusData {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *IntegrationStatusResponse) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *IntegrationStatusResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntegrationStatusResponse) SetSuccess(success *bool) {
	i.Success = success
	i.require(integrationStatusResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntegrationStatusResponse) SetTimestamp(timestamp *time.Time) {
	i.Timestamp = timestamp
	i.require(integrationStatusResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IntegrationStatusResponse) SetData(data *IntegrationStatusData) {
	i.Data = data
	i.require(integrationStatusResponseFieldData)
}

func (i *IntegrationStatusResponse) UnmarshalJSON(data []byte) error {
	type embed IntegrationStatusResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = IntegrationStatusResponse(unmarshaler.embed)
	i.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntegrationStatusResponse) MarshalJSON() ([]byte, error) {
	type embed IntegrationStatusResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*i),
		Timestamp: internal.NewOptionalDateTime(i.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IntegrationStatusResponse) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Onboarding mode. AWS: single|organization. GitHub: github_app.
type CreateIntegrationRequestMode string

const (
	CreateIntegrationRequestModeSingle       CreateIntegrationRequestMode = "single"
	CreateIntegrationRequestModeOrganization CreateIntegrationRequestMode = "organization"
	CreateIntegrationRequestModeGithubApp    CreateIntegrationRequestMode = "github_app"
)

func NewCreateIntegrationRequestModeFromString(s string) (CreateIntegrationRequestMode, error) {
	switch s {
	case "single":
		return CreateIntegrationRequestModeSingle, nil
	case "organization":
		return CreateIntegrationRequestModeOrganization, nil
	case "github_app":
		return CreateIntegrationRequestModeGithubApp, nil
	}
	var t CreateIntegrationRequestMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateIntegrationRequestMode) Ptr() *CreateIntegrationRequestMode {
	return &c
}

// Cloud provider identifier
type CreateIntegrationRequestProvider string

const (
	CreateIntegrationRequestProviderAws    CreateIntegrationRequestProvider = "aws"
	CreateIntegrationRequestProviderGithub CreateIntegrationRequestProvider = "github"
)

func NewCreateIntegrationRequestProviderFromString(s string) (CreateIntegrationRequestProvider, error) {
	switch s {
	case "aws":
		return CreateIntegrationRequestProviderAws, nil
	case "github":
		return CreateIntegrationRequestProviderGithub, nil
	}
	var t CreateIntegrationRequestProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateIntegrationRequestProvider) Ptr() *CreateIntegrationRequestProvider {
	return &c
}

// GitHub Setup URL action. install on first install, update when repos/permissions changed.
type GithubCompleteRequestSetupAction string

const (
	GithubCompleteRequestSetupActionInstall GithubCompleteRequestSetupAction = "install"
	GithubCompleteRequestSetupActionUpdate  GithubCompleteRequestSetupAction = "update"
)

func NewGithubCompleteRequestSetupActionFromString(s string) (GithubCompleteRequestSetupAction, error) {
	switch s {
	case "install":
		return GithubCompleteRequestSetupActionInstall, nil
	case "update":
		return GithubCompleteRequestSetupActionUpdate, nil
	}
	var t GithubCompleteRequestSetupAction
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GithubCompleteRequestSetupAction) Ptr() *GithubCompleteRequestSetupAction {
	return &g
}
