// Code generated by Fern. DO NOT EDIT.

package levelfour

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersCloudAccountData(t *testing.T) {
	t.Run("SetName", func(t *testing.T) {
		obj := &CloudAccountData{}
		var fernTestValueName string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProvider", func(t *testing.T) {
		obj := &CloudAccountData{}
		var fernTestValueProvider string
		obj.SetProvider(fernTestValueProvider)
		assert.Equal(t, fernTestValueProvider, obj.Provider)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAccountID", func(t *testing.T) {
		obj := &CloudAccountData{}
		var fernTestValueAccountID string
		obj.SetAccountID(fernTestValueAccountID)
		assert.Equal(t, fernTestValueAccountID, obj.AccountID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCloudAccountData(t *testing.T) {
	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CloudAccountData{}
		var expected string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CloudAccountData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetProvider", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CloudAccountData{}
		var expected string
		obj.Provider = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProvider(), "getter should return the property value")
	})

	t.Run("GetProvider_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CloudAccountData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProvider() // Should return zero value
	})

	t.Run("GetAccountID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CloudAccountData{}
		var expected string
		obj.AccountID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAccountID(), "getter should return the property value")
	})

	t.Run("GetAccountID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CloudAccountData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAccountID() // Should return zero value
	})

}

func TestSettersMarkExplicitCloudAccountData(t *testing.T) {
	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CloudAccountData{}
		var fernTestValueName string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CloudAccountData{}
		var fernTestValueProvider string

		// Act
		obj.SetProvider(fernTestValueProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAccountID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CloudAccountData{}
		var fernTestValueAccountID string

		// Act
		obj.SetAccountID(fernTestValueAccountID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWhoamiData(t *testing.T) {
	t.Run("SetOrganization", func(t *testing.T) {
		obj := &WhoamiData{}
		var fernTestValueOrganization string
		obj.SetOrganization(fernTestValueOrganization)
		assert.Equal(t, fernTestValueOrganization, obj.Organization)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPlan", func(t *testing.T) {
		obj := &WhoamiData{}
		var fernTestValuePlan string
		obj.SetPlan(fernTestValuePlan)
		assert.Equal(t, fernTestValuePlan, obj.Plan)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRole", func(t *testing.T) {
		obj := &WhoamiData{}
		var fernTestValueRole string
		obj.SetRole(fernTestValueRole)
		assert.Equal(t, fernTestValueRole, obj.Role)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAccounts", func(t *testing.T) {
		obj := &WhoamiData{}
		var fernTestValueAccounts []*CloudAccountData
		obj.SetAccounts(fernTestValueAccounts)
		assert.Equal(t, fernTestValueAccounts, obj.Accounts)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersWhoamiData(t *testing.T) {
	t.Run("GetOrganization", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiData{}
		var expected string
		obj.Organization = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOrganization(), "getter should return the property value")
	})

	t.Run("GetOrganization_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WhoamiData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOrganization() // Should return zero value
	})

	t.Run("GetPlan", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiData{}
		var expected string
		obj.Plan = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPlan(), "getter should return the property value")
	})

	t.Run("GetPlan_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WhoamiData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPlan() // Should return zero value
	})

	t.Run("GetRole", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiData{}
		var expected string
		obj.Role = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRole(), "getter should return the property value")
	})

	t.Run("GetRole_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WhoamiData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRole() // Should return zero value
	})

	t.Run("GetAccounts", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiData{}
		var expected []*CloudAccountData
		obj.Accounts = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAccounts(), "getter should return the property value")
	})

	t.Run("GetAccounts_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiData{}
		obj.Accounts = nil

		// Act & Assert
		assert.Nil(t, obj.GetAccounts(), "getter should return nil when property is nil")
	})

	t.Run("GetAccounts_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WhoamiData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAccounts() // Should return zero value
	})

}

func TestSettersMarkExplicitWhoamiData(t *testing.T) {
	t.Run("SetOrganization_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiData{}
		var fernTestValueOrganization string

		// Act
		obj.SetOrganization(fernTestValueOrganization)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPlan_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiData{}
		var fernTestValuePlan string

		// Act
		obj.SetPlan(fernTestValuePlan)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRole_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiData{}
		var fernTestValueRole string

		// Act
		obj.SetRole(fernTestValueRole)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAccounts_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiData{}
		var fernTestValueAccounts []*CloudAccountData

		// Act
		obj.SetAccounts(fernTestValueAccounts)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWhoamiResponse(t *testing.T) {
	t.Run("SetSuccess", func(t *testing.T) {
		obj := &WhoamiResponse{}
		var fernTestValueSuccess *bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTimestamp", func(t *testing.T) {
		obj := &WhoamiResponse{}
		var fernTestValueTimestamp *time.Time
		obj.SetTimestamp(fernTestValueTimestamp)
		assert.Equal(t, fernTestValueTimestamp, obj.Timestamp)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetData", func(t *testing.T) {
		obj := &WhoamiResponse{}
		var fernTestValueData *WhoamiData
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersWhoamiResponse(t *testing.T) {
	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiResponse{}
		var expected *bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiResponse{}
		obj.Success = nil

		// Act & Assert
		assert.Nil(t, obj.GetSuccess(), "getter should return nil when property is nil")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WhoamiResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

	t.Run("GetTimestamp", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiResponse{}
		var expected *time.Time
		obj.Timestamp = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTimestamp(), "getter should return the property value")
	})

	t.Run("GetTimestamp_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiResponse{}
		obj.Timestamp = nil

		// Act & Assert
		assert.Nil(t, obj.GetTimestamp(), "getter should return nil when property is nil")
	})

	t.Run("GetTimestamp_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WhoamiResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTimestamp() // Should return zero value
	})

	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiResponse{}
		var expected *WhoamiData
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiResponse{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WhoamiResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

}

func TestSettersMarkExplicitWhoamiResponse(t *testing.T) {
	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiResponse{}
		var fernTestValueSuccess *bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTimestamp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiResponse{}
		var fernTestValueTimestamp *time.Time

		// Act
		obj.SetTimestamp(fernTestValueTimestamp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiResponse{}
		var fernTestValueData *WhoamiData

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingCloudAccountData(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CloudAccountData{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CloudAccountData
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CloudAccountData
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CloudAccountData
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingWhoamiData(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiData{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled WhoamiData
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj WhoamiData
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj WhoamiData
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingWhoamiResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WhoamiResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled WhoamiResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj WhoamiResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj WhoamiResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringCloudAccountData(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CloudAccountData{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CloudAccountData
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringWhoamiData(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &WhoamiData{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WhoamiData
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringWhoamiResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &WhoamiResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WhoamiResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesCloudAccountData(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CloudAccountData{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CloudAccountData
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesWhoamiData(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &WhoamiData{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WhoamiData
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesWhoamiResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &WhoamiResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WhoamiResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
