// Code generated by Fern. DO NOT EDIT.

package levelfour

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/LevelFourAI/levelfour-go/internal"
	big "math/big"
	time "time"
)

var (
	createBoardRequestFieldName       = big.NewInt(1 << 0)
	createBoardRequestFieldTemplateID = big.NewInt(1 << 1)
	createBoardRequestFieldDotColor   = big.NewInt(1 << 2)
)

type CreateBoardRequest struct {
	Name       string  `json:"name" url:"-"`
	TemplateID *string `json:"template_id,omitempty" url:"-"`
	DotColor   *string `json:"dot_color,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateBoardRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBoardRequest) SetName(name string) {
	c.Name = name
	c.require(createBoardRequestFieldName)
}

// SetTemplateID sets the TemplateID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBoardRequest) SetTemplateID(templateID *string) {
	c.TemplateID = templateID
	c.require(createBoardRequestFieldTemplateID)
}

// SetDotColor sets the DotColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateBoardRequest) SetDotColor(dotColor *string) {
	c.DotColor = dotColor
	c.require(createBoardRequestFieldDotColor)
}

func (c *CreateBoardRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateBoardRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateBoardRequest(body)
	return nil
}

func (c *CreateBoardRequest) MarshalJSON() ([]byte, error) {
	type embed CreateBoardRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	boardFieldID             = big.NewInt(1 << 0)
	boardFieldTenantID       = big.NewInt(1 << 1)
	boardFieldUserID         = big.NewInt(1 << 2)
	boardFieldName           = big.NewInt(1 << 3)
	boardFieldTemplateID     = big.NewInt(1 << 4)
	boardFieldIsPinned       = big.NewInt(1 << 5)
	boardFieldDotColor       = big.NewInt(1 << 6)
	boardFieldLayout         = big.NewInt(1 << 7)
	boardFieldKpiStripConfig = big.NewInt(1 << 8)
	boardFieldCreatedAt      = big.NewInt(1 << 9)
	boardFieldUpdatedAt      = big.NewInt(1 << 10)
)

type Board struct {
	ID             string          `json:"id" url:"id"`
	TenantID       int             `json:"tenant_id" url:"tenant_id"`
	UserID         string          `json:"user_id" url:"user_id"`
	Name           string          `json:"name" url:"name"`
	TemplateID     *string         `json:"template_id,omitempty" url:"template_id,omitempty"`
	IsPinned       *bool           `json:"is_pinned,omitempty" url:"is_pinned,omitempty"`
	DotColor       *string         `json:"dot_color,omitempty" url:"dot_color,omitempty"`
	Layout         []*CardLayout   `json:"layout,omitempty" url:"layout,omitempty"`
	KpiStripConfig *KpiStripConfig `json:"kpi_strip_config,omitempty" url:"kpi_strip_config,omitempty"`
	CreatedAt      time.Time       `json:"created_at" url:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *Board) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *Board) GetTenantID() int {
	if b == nil {
		return 0
	}
	return b.TenantID
}

func (b *Board) GetUserID() string {
	if b == nil {
		return ""
	}
	return b.UserID
}

func (b *Board) GetName() string {
	if b == nil {
		return ""
	}
	return b.Name
}

func (b *Board) GetTemplateID() *string {
	if b == nil {
		return nil
	}
	return b.TemplateID
}

func (b *Board) GetIsPinned() *bool {
	if b == nil {
		return nil
	}
	return b.IsPinned
}

func (b *Board) GetDotColor() *string {
	if b == nil {
		return nil
	}
	return b.DotColor
}

func (b *Board) GetLayout() []*CardLayout {
	if b == nil {
		return nil
	}
	return b.Layout
}

func (b *Board) GetKpiStripConfig() *KpiStripConfig {
	if b == nil {
		return nil
	}
	return b.KpiStripConfig
}

func (b *Board) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}

func (b *Board) GetUpdatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.UpdatedAt
}

func (b *Board) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *Board) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Board) SetID(id string) {
	b.ID = id
	b.require(boardFieldID)
}

// SetTenantID sets the TenantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Board) SetTenantID(tenantID int) {
	b.TenantID = tenantID
	b.require(boardFieldTenantID)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Board) SetUserID(userID string) {
	b.UserID = userID
	b.require(boardFieldUserID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Board) SetName(name string) {
	b.Name = name
	b.require(boardFieldName)
}

// SetTemplateID sets the TemplateID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Board) SetTemplateID(templateID *string) {
	b.TemplateID = templateID
	b.require(boardFieldTemplateID)
}

// SetIsPinned sets the IsPinned field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Board) SetIsPinned(isPinned *bool) {
	b.IsPinned = isPinned
	b.require(boardFieldIsPinned)
}

// SetDotColor sets the DotColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Board) SetDotColor(dotColor *string) {
	b.DotColor = dotColor
	b.require(boardFieldDotColor)
}

// SetLayout sets the Layout field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Board) SetLayout(layout []*CardLayout) {
	b.Layout = layout
	b.require(boardFieldLayout)
}

// SetKpiStripConfig sets the KpiStripConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Board) SetKpiStripConfig(kpiStripConfig *KpiStripConfig) {
	b.KpiStripConfig = kpiStripConfig
	b.require(boardFieldKpiStripConfig)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Board) SetCreatedAt(createdAt time.Time) {
	b.CreatedAt = createdAt
	b.require(boardFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *Board) SetUpdatedAt(updatedAt time.Time) {
	b.UpdatedAt = updatedAt
	b.require(boardFieldUpdatedAt)
}

func (b *Board) UnmarshalJSON(data []byte) error {
	type embed Board
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*b),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*b = Board(unmarshaler.embed)
	b.CreatedAt = unmarshaler.CreatedAt.Time()
	b.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *Board) MarshalJSON() ([]byte, error) {
	type embed Board
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed:     embed(*b),
		CreatedAt: internal.NewDateTime(b.CreatedAt),
		UpdatedAt: internal.NewDateTime(b.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *Board) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	boardListItemFieldID         = big.NewInt(1 << 0)
	boardListItemFieldName       = big.NewInt(1 << 1)
	boardListItemFieldTemplateID = big.NewInt(1 << 2)
	boardListItemFieldIsPinned   = big.NewInt(1 << 3)
	boardListItemFieldDotColor   = big.NewInt(1 << 4)
	boardListItemFieldUpdatedAt  = big.NewInt(1 << 5)
)

type BoardListItem struct {
	ID         string    `json:"id" url:"id"`
	Name       string    `json:"name" url:"name"`
	TemplateID *string   `json:"template_id,omitempty" url:"template_id,omitempty"`
	IsPinned   *bool     `json:"is_pinned,omitempty" url:"is_pinned,omitempty"`
	DotColor   *string   `json:"dot_color,omitempty" url:"dot_color,omitempty"`
	UpdatedAt  time.Time `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BoardListItem) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BoardListItem) GetName() string {
	if b == nil {
		return ""
	}
	return b.Name
}

func (b *BoardListItem) GetTemplateID() *string {
	if b == nil {
		return nil
	}
	return b.TemplateID
}

func (b *BoardListItem) GetIsPinned() *bool {
	if b == nil {
		return nil
	}
	return b.IsPinned
}

func (b *BoardListItem) GetDotColor() *string {
	if b == nil {
		return nil
	}
	return b.DotColor
}

func (b *BoardListItem) GetUpdatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.UpdatedAt
}

func (b *BoardListItem) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BoardListItem) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoardListItem) SetID(id string) {
	b.ID = id
	b.require(boardListItemFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoardListItem) SetName(name string) {
	b.Name = name
	b.require(boardListItemFieldName)
}

// SetTemplateID sets the TemplateID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoardListItem) SetTemplateID(templateID *string) {
	b.TemplateID = templateID
	b.require(boardListItemFieldTemplateID)
}

// SetIsPinned sets the IsPinned field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoardListItem) SetIsPinned(isPinned *bool) {
	b.IsPinned = isPinned
	b.require(boardListItemFieldIsPinned)
}

// SetDotColor sets the DotColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoardListItem) SetDotColor(dotColor *string) {
	b.DotColor = dotColor
	b.require(boardListItemFieldDotColor)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoardListItem) SetUpdatedAt(updatedAt time.Time) {
	b.UpdatedAt = updatedAt
	b.require(boardListItemFieldUpdatedAt)
}

func (b *BoardListItem) UnmarshalJSON(data []byte) error {
	type embed BoardListItem
	var unmarshaler = struct {
		embed
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*b),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*b = BoardListItem(unmarshaler.embed)
	b.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BoardListItem) MarshalJSON() ([]byte, error) {
	type embed BoardListItem
	var marshaler = struct {
		embed
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed:     embed(*b),
		UpdatedAt: internal.NewDateTime(b.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BoardListItem) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	boardListResponseFieldSuccess   = big.NewInt(1 << 0)
	boardListResponseFieldTimestamp = big.NewInt(1 << 1)
	boardListResponseFieldData      = big.NewInt(1 << 2)
)

type BoardListResponse struct {
	Success   *bool            `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time       `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      []*BoardListItem `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BoardListResponse) GetSuccess() *bool {
	if b == nil {
		return nil
	}
	return b.Success
}

func (b *BoardListResponse) GetTimestamp() *time.Time {
	if b == nil {
		return nil
	}
	return b.Timestamp
}

func (b *BoardListResponse) GetData() []*BoardListItem {
	if b == nil {
		return nil
	}
	return b.Data
}

func (b *BoardListResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BoardListResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoardListResponse) SetSuccess(success *bool) {
	b.Success = success
	b.require(boardListResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoardListResponse) SetTimestamp(timestamp *time.Time) {
	b.Timestamp = timestamp
	b.require(boardListResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoardListResponse) SetData(data []*BoardListItem) {
	b.Data = data
	b.require(boardListResponseFieldData)
}

func (b *BoardListResponse) UnmarshalJSON(data []byte) error {
	type embed BoardListResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*b),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*b = BoardListResponse(unmarshaler.embed)
	b.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BoardListResponse) MarshalJSON() ([]byte, error) {
	type embed BoardListResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*b),
		Timestamp: internal.NewOptionalDateTime(b.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BoardListResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	boardResponseFieldSuccess   = big.NewInt(1 << 0)
	boardResponseFieldTimestamp = big.NewInt(1 << 1)
	boardResponseFieldData      = big.NewInt(1 << 2)
)

type BoardResponse struct {
	Success   *bool      `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *Board     `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BoardResponse) GetSuccess() *bool {
	if b == nil {
		return nil
	}
	return b.Success
}

func (b *BoardResponse) GetTimestamp() *time.Time {
	if b == nil {
		return nil
	}
	return b.Timestamp
}

func (b *BoardResponse) GetData() *Board {
	if b == nil {
		return nil
	}
	return b.Data
}

func (b *BoardResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BoardResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoardResponse) SetSuccess(success *bool) {
	b.Success = success
	b.require(boardResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoardResponse) SetTimestamp(timestamp *time.Time) {
	b.Timestamp = timestamp
	b.require(boardResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoardResponse) SetData(data *Board) {
	b.Data = data
	b.require(boardResponseFieldData)
}

func (b *BoardResponse) UnmarshalJSON(data []byte) error {
	type embed BoardResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*b),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*b = BoardResponse(unmarshaler.embed)
	b.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BoardResponse) MarshalJSON() ([]byte, error) {
	type embed BoardResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*b),
		Timestamp: internal.NewOptionalDateTime(b.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BoardResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	cardLayoutFieldCardID    = big.NewInt(1 << 0)
	cardLayoutFieldRow       = big.NewInt(1 << 1)
	cardLayoutFieldSpan      = big.NewInt(1 << 2)
	cardLayoutFieldOverrides = big.NewInt(1 << 3)
)

type CardLayout struct {
	CardID    string         `json:"card_id" url:"card_id"`
	Row       int            `json:"row" url:"row"`
	Span      int            `json:"span" url:"span"`
	Overrides map[string]any `json:"overrides,omitempty" url:"overrides,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CardLayout) GetCardID() string {
	if c == nil {
		return ""
	}
	return c.CardID
}

func (c *CardLayout) GetRow() int {
	if c == nil {
		return 0
	}
	return c.Row
}

func (c *CardLayout) GetSpan() int {
	if c == nil {
		return 0
	}
	return c.Span
}

func (c *CardLayout) GetOverrides() map[string]any {
	if c == nil {
		return nil
	}
	return c.Overrides
}

func (c *CardLayout) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CardLayout) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetCardID sets the CardID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CardLayout) SetCardID(cardID string) {
	c.CardID = cardID
	c.require(cardLayoutFieldCardID)
}

// SetRow sets the Row field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CardLayout) SetRow(row int) {
	c.Row = row
	c.require(cardLayoutFieldRow)
}

// SetSpan sets the Span field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CardLayout) SetSpan(span int) {
	c.Span = span
	c.require(cardLayoutFieldSpan)
}

// SetOverrides sets the Overrides field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CardLayout) SetOverrides(overrides map[string]any) {
	c.Overrides = overrides
	c.require(cardLayoutFieldOverrides)
}

func (c *CardLayout) UnmarshalJSON(data []byte) error {
	type unmarshaler CardLayout
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CardLayout(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CardLayout) MarshalJSON() ([]byte, error) {
	type embed CardLayout
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CardLayout) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	kpiStripConfigFieldCells = big.NewInt(1 << 0)
)

type KpiStripConfig struct {
	Cells []string `json:"cells" url:"cells"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (k *KpiStripConfig) GetCells() []string {
	if k == nil {
		return nil
	}
	return k.Cells
}

func (k *KpiStripConfig) GetExtraProperties() map[string]interface{} {
	if k == nil {
		return nil
	}
	return k.extraProperties
}

func (k *KpiStripConfig) require(field *big.Int) {
	if k.explicitFields == nil {
		k.explicitFields = big.NewInt(0)
	}
	k.explicitFields.Or(k.explicitFields, field)
}

// SetCells sets the Cells field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KpiStripConfig) SetCells(cells []string) {
	k.Cells = cells
	k.require(kpiStripConfigFieldCells)
}

func (k *KpiStripConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler KpiStripConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*k = KpiStripConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *k)
	if err != nil {
		return err
	}
	k.extraProperties = extraProperties
	k.rawJSON = json.RawMessage(data)
	return nil
}

func (k *KpiStripConfig) MarshalJSON() ([]byte, error) {
	type embed KpiStripConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*k),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, k.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (k *KpiStripConfig) String() string {
	if k == nil {
		return "<nil>"
	}
	if len(k.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(k.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(k); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", k)
}

var (
	templateInfoFieldTemplateID    = big.NewInt(1 << 0)
	templateInfoFieldName          = big.NewInt(1 << 1)
	templateInfoFieldDotColor      = big.NewInt(1 << 2)
	templateInfoFieldDefaultPinned = big.NewInt(1 << 3)
)

type TemplateInfo struct {
	TemplateID    string `json:"template_id" url:"template_id"`
	Name          string `json:"name" url:"name"`
	DotColor      string `json:"dot_color" url:"dot_color"`
	DefaultPinned bool   `json:"default_pinned" url:"default_pinned"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TemplateInfo) GetTemplateID() string {
	if t == nil {
		return ""
	}
	return t.TemplateID
}

func (t *TemplateInfo) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TemplateInfo) GetDotColor() string {
	if t == nil {
		return ""
	}
	return t.DotColor
}

func (t *TemplateInfo) GetDefaultPinned() bool {
	if t == nil {
		return false
	}
	return t.DefaultPinned
}

func (t *TemplateInfo) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TemplateInfo) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetTemplateID sets the TemplateID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TemplateInfo) SetTemplateID(templateID string) {
	t.TemplateID = templateID
	t.require(templateInfoFieldTemplateID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TemplateInfo) SetName(name string) {
	t.Name = name
	t.require(templateInfoFieldName)
}

// SetDotColor sets the DotColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TemplateInfo) SetDotColor(dotColor string) {
	t.DotColor = dotColor
	t.require(templateInfoFieldDotColor)
}

// SetDefaultPinned sets the DefaultPinned field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TemplateInfo) SetDefaultPinned(defaultPinned bool) {
	t.DefaultPinned = defaultPinned
	t.require(templateInfoFieldDefaultPinned)
}

func (t *TemplateInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler TemplateInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TemplateInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TemplateInfo) MarshalJSON() ([]byte, error) {
	type embed TemplateInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TemplateInfo) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	templateListResponseFieldSuccess   = big.NewInt(1 << 0)
	templateListResponseFieldTimestamp = big.NewInt(1 << 1)
	templateListResponseFieldData      = big.NewInt(1 << 2)
)

type TemplateListResponse struct {
	Success   *bool           `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time      `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      []*TemplateInfo `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TemplateListResponse) GetSuccess() *bool {
	if t == nil {
		return nil
	}
	return t.Success
}

func (t *TemplateListResponse) GetTimestamp() *time.Time {
	if t == nil {
		return nil
	}
	return t.Timestamp
}

func (t *TemplateListResponse) GetData() []*TemplateInfo {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TemplateListResponse) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TemplateListResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TemplateListResponse) SetSuccess(success *bool) {
	t.Success = success
	t.require(templateListResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TemplateListResponse) SetTimestamp(timestamp *time.Time) {
	t.Timestamp = timestamp
	t.require(templateListResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TemplateListResponse) SetData(data []*TemplateInfo) {
	t.Data = data
	t.require(templateListResponseFieldData)
}

func (t *TemplateListResponse) UnmarshalJSON(data []byte) error {
	type embed TemplateListResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TemplateListResponse(unmarshaler.embed)
	t.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TemplateListResponse) MarshalJSON() ([]byte, error) {
	type embed TemplateListResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*t),
		Timestamp: internal.NewOptionalDateTime(t.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TemplateListResponse) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	updateBoardRequestFieldName     = big.NewInt(1 << 0)
	updateBoardRequestFieldDotColor = big.NewInt(1 << 1)
	updateBoardRequestFieldIsPinned = big.NewInt(1 << 2)
)

type UpdateBoardRequest struct {
	Name     *string `json:"name,omitempty" url:"-"`
	DotColor *string `json:"dot_color,omitempty" url:"-"`
	IsPinned *bool   `json:"is_pinned,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateBoardRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBoardRequest) SetName(name *string) {
	u.Name = name
	u.require(updateBoardRequestFieldName)
}

// SetDotColor sets the DotColor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBoardRequest) SetDotColor(dotColor *string) {
	u.DotColor = dotColor
	u.require(updateBoardRequestFieldDotColor)
}

// SetIsPinned sets the IsPinned field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateBoardRequest) SetIsPinned(isPinned *bool) {
	u.IsPinned = isPinned
	u.require(updateBoardRequestFieldIsPinned)
}

func (u *UpdateBoardRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateBoardRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateBoardRequest(body)
	return nil
}

func (u *UpdateBoardRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateBoardRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	updateKpiStripRequestFieldCells = big.NewInt(1 << 0)
)

type UpdateKpiStripRequest struct {
	Cells []string `json:"cells" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateKpiStripRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetCells sets the Cells field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateKpiStripRequest) SetCells(cells []string) {
	u.Cells = cells
	u.require(updateKpiStripRequestFieldCells)
}

func (u *UpdateKpiStripRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateKpiStripRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateKpiStripRequest(body)
	return nil
}

func (u *UpdateKpiStripRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateKpiStripRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	updateLayoutRequestFieldLayout = big.NewInt(1 << 0)
)

type UpdateLayoutRequest struct {
	Layout []*CardLayout `json:"layout" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateLayoutRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetLayout sets the Layout field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateLayoutRequest) SetLayout(layout []*CardLayout) {
	u.Layout = layout
	u.require(updateLayoutRequestFieldLayout)
}

func (u *UpdateLayoutRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateLayoutRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateLayoutRequest(body)
	return nil
}

func (u *UpdateLayoutRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateLayoutRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
