// Code generated by Fern. DO NOT EDIT.

package levelfour

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersConnectionResponse(t *testing.T) {
	t.Run("SetSuccess", func(t *testing.T) {
		obj := &ConnectionResponse{}
		var fernTestValueSuccess *bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetData", func(t *testing.T) {
		obj := &ConnectionResponse{}
		var fernTestValueData *ConnectionSchema
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTimestamp", func(t *testing.T) {
		obj := &ConnectionResponse{}
		var fernTestValueTimestamp string
		obj.SetTimestamp(fernTestValueTimestamp)
		assert.Equal(t, fernTestValueTimestamp, obj.Timestamp)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersConnectionResponse(t *testing.T) {
	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionResponse{}
		var expected *bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionResponse{}
		obj.Success = nil

		// Act & Assert
		assert.Nil(t, obj.GetSuccess(), "getter should return nil when property is nil")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionResponse{}
		var expected *ConnectionSchema
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionResponse{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

	t.Run("GetTimestamp", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionResponse{}
		var expected string
		obj.Timestamp = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTimestamp(), "getter should return the property value")
	})

	t.Run("GetTimestamp_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTimestamp() // Should return zero value
	})

}

func TestSettersMarkExplicitConnectionResponse(t *testing.T) {
	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionResponse{}
		var fernTestValueSuccess *bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionResponse{}
		var fernTestValueData *ConnectionSchema

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTimestamp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionResponse{}
		var fernTestValueTimestamp string

		// Act
		obj.SetTimestamp(fernTestValueTimestamp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersConnectionSchema(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProvider", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueProvider string
		obj.SetProvider(fernTestValueProvider)
		assert.Equal(t, fernTestValueProvider, obj.Provider)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSource", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueSource string
		obj.SetSource(fernTestValueSource)
		assert.Equal(t, fernTestValueSource, obj.Source)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDisplayName", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueDisplayName string
		obj.SetDisplayName(fernTestValueDisplayName)
		assert.Equal(t, fernTestValueDisplayName, obj.DisplayName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueStatus string
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatusReason", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueStatusReason *string
		obj.SetStatusReason(fernTestValueStatusReason)
		assert.Equal(t, fernTestValueStatusReason, obj.StatusReason)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBillingAccountID", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueBillingAccountID *string
		obj.SetBillingAccountID(fernTestValueBillingAccountID)
		assert.Equal(t, fernTestValueBillingAccountID, obj.BillingAccountID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBillingAccountName", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueBillingAccountName *string
		obj.SetBillingAccountName(fernTestValueBillingAccountName)
		assert.Equal(t, fernTestValueBillingAccountName, obj.BillingAccountName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBilledVia", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueBilledVia *string
		obj.SetBilledVia(fernTestValueBilledVia)
		assert.Equal(t, fernTestValueBilledVia, obj.BilledVia)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCredentialFingerprint", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueCredentialFingerprint *string
		obj.SetCredentialFingerprint(fernTestValueCredentialFingerprint)
		assert.Equal(t, fernTestValueCredentialFingerprint, obj.CredentialFingerprint)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCredentialHint", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueCredentialHint *string
		obj.SetCredentialHint(fernTestValueCredentialHint)
		assert.Equal(t, fernTestValueCredentialHint, obj.CredentialHint)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCredentialExpiresAt", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueCredentialExpiresAt *time.Time
		obj.SetCredentialExpiresAt(fernTestValueCredentialExpiresAt)
		assert.Equal(t, fernTestValueCredentialExpiresAt, obj.CredentialExpiresAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLastSuccessAt", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueLastSuccessAt *time.Time
		obj.SetLastSuccessAt(fernTestValueLastSuccessAt)
		assert.Equal(t, fernTestValueLastSuccessAt, obj.LastSuccessAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNextSyncAt", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueNextSyncAt *time.Time
		obj.SetNextSyncAt(fernTestValueNextSyncAt)
		assert.Equal(t, fernTestValueNextSyncAt, obj.NextSyncAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBackfillCompleteAt", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueBackfillCompleteAt *time.Time
		obj.SetBackfillCompleteAt(fernTestValueBackfillCompleteAt)
		assert.Equal(t, fernTestValueBackfillCompleteAt, obj.BackfillCompleteAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueCreatedAt *time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetConfig", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueConfig map[string]any
		obj.SetConfig(fernTestValueConfig)
		assert.Equal(t, fernTestValueConfig, obj.Config)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDataGrain", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueDataGrain *string
		obj.SetDataGrain(fernTestValueDataGrain)
		assert.Equal(t, fernTestValueDataGrain, obj.DataGrain)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFirstDataEta", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueFirstDataEta *string
		obj.SetFirstDataEta(fernTestValueFirstDataEta)
		assert.Equal(t, fernTestValueFirstDataEta, obj.FirstDataEta)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCoverageExcludes", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueCoverageExcludes []string
		obj.SetCoverageExcludes(fernTestValueCoverageExcludes)
		assert.Equal(t, fernTestValueCoverageExcludes, obj.CoverageExcludes)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCostBasisClass", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueCostBasisClass *string
		obj.SetCostBasisClass(fernTestValueCostBasisClass)
		assert.Equal(t, fernTestValueCostBasisClass, obj.CostBasisClass)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSetupScript", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueSetupScript *string
		obj.SetSetupScript(fernTestValueSetupScript)
		assert.Equal(t, fernTestValueSetupScript, obj.SetupScript)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEvents", func(t *testing.T) {
		obj := &ConnectionSchema{}
		var fernTestValueEvents []map[string]any
		obj.SetEvents(fernTestValueEvents)
		assert.Equal(t, fernTestValueEvents, obj.Events)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersConnectionSchema(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetProvider", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected string
		obj.Provider = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProvider(), "getter should return the property value")
	})

	t.Run("GetProvider_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProvider() // Should return zero value
	})

	t.Run("GetSource", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected string
		obj.Source = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSource(), "getter should return the property value")
	})

	t.Run("GetSource_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSource() // Should return zero value
	})

	t.Run("GetDisplayName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected string
		obj.DisplayName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDisplayName(), "getter should return the property value")
	})

	t.Run("GetDisplayName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDisplayName() // Should return zero value
	})

	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected string
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

	t.Run("GetStatusReason", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *string
		obj.StatusReason = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatusReason(), "getter should return the property value")
	})

	t.Run("GetStatusReason_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.StatusReason = nil

		// Act & Assert
		assert.Nil(t, obj.GetStatusReason(), "getter should return nil when property is nil")
	})

	t.Run("GetStatusReason_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatusReason() // Should return zero value
	})

	t.Run("GetBillingAccountID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *string
		obj.BillingAccountID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBillingAccountID(), "getter should return the property value")
	})

	t.Run("GetBillingAccountID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.BillingAccountID = nil

		// Act & Assert
		assert.Nil(t, obj.GetBillingAccountID(), "getter should return nil when property is nil")
	})

	t.Run("GetBillingAccountID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBillingAccountID() // Should return zero value
	})

	t.Run("GetBillingAccountName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *string
		obj.BillingAccountName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBillingAccountName(), "getter should return the property value")
	})

	t.Run("GetBillingAccountName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.BillingAccountName = nil

		// Act & Assert
		assert.Nil(t, obj.GetBillingAccountName(), "getter should return nil when property is nil")
	})

	t.Run("GetBillingAccountName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBillingAccountName() // Should return zero value
	})

	t.Run("GetBilledVia", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *string
		obj.BilledVia = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBilledVia(), "getter should return the property value")
	})

	t.Run("GetBilledVia_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.BilledVia = nil

		// Act & Assert
		assert.Nil(t, obj.GetBilledVia(), "getter should return nil when property is nil")
	})

	t.Run("GetBilledVia_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBilledVia() // Should return zero value
	})

	t.Run("GetCredentialFingerprint", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *string
		obj.CredentialFingerprint = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCredentialFingerprint(), "getter should return the property value")
	})

	t.Run("GetCredentialFingerprint_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.CredentialFingerprint = nil

		// Act & Assert
		assert.Nil(t, obj.GetCredentialFingerprint(), "getter should return nil when property is nil")
	})

	t.Run("GetCredentialFingerprint_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCredentialFingerprint() // Should return zero value
	})

	t.Run("GetCredentialHint", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *string
		obj.CredentialHint = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCredentialHint(), "getter should return the property value")
	})

	t.Run("GetCredentialHint_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.CredentialHint = nil

		// Act & Assert
		assert.Nil(t, obj.GetCredentialHint(), "getter should return nil when property is nil")
	})

	t.Run("GetCredentialHint_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCredentialHint() // Should return zero value
	})

	t.Run("GetCredentialExpiresAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *time.Time
		obj.CredentialExpiresAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCredentialExpiresAt(), "getter should return the property value")
	})

	t.Run("GetCredentialExpiresAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.CredentialExpiresAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetCredentialExpiresAt(), "getter should return nil when property is nil")
	})

	t.Run("GetCredentialExpiresAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCredentialExpiresAt() // Should return zero value
	})

	t.Run("GetLastSuccessAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *time.Time
		obj.LastSuccessAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLastSuccessAt(), "getter should return the property value")
	})

	t.Run("GetLastSuccessAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.LastSuccessAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetLastSuccessAt(), "getter should return nil when property is nil")
	})

	t.Run("GetLastSuccessAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLastSuccessAt() // Should return zero value
	})

	t.Run("GetNextSyncAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *time.Time
		obj.NextSyncAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNextSyncAt(), "getter should return the property value")
	})

	t.Run("GetNextSyncAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.NextSyncAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetNextSyncAt(), "getter should return nil when property is nil")
	})

	t.Run("GetNextSyncAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNextSyncAt() // Should return zero value
	})

	t.Run("GetBackfillCompleteAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *time.Time
		obj.BackfillCompleteAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBackfillCompleteAt(), "getter should return the property value")
	})

	t.Run("GetBackfillCompleteAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.BackfillCompleteAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetBackfillCompleteAt(), "getter should return nil when property is nil")
	})

	t.Run("GetBackfillCompleteAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBackfillCompleteAt() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.CreatedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetCreatedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetConfig", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected map[string]any
		obj.Config = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetConfig(), "getter should return the property value")
	})

	t.Run("GetConfig_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.Config = nil

		// Act & Assert
		assert.Nil(t, obj.GetConfig(), "getter should return nil when property is nil")
	})

	t.Run("GetConfig_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetConfig() // Should return zero value
	})

	t.Run("GetDataGrain", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *string
		obj.DataGrain = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDataGrain(), "getter should return the property value")
	})

	t.Run("GetDataGrain_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.DataGrain = nil

		// Act & Assert
		assert.Nil(t, obj.GetDataGrain(), "getter should return nil when property is nil")
	})

	t.Run("GetDataGrain_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDataGrain() // Should return zero value
	})

	t.Run("GetFirstDataEta", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *string
		obj.FirstDataEta = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFirstDataEta(), "getter should return the property value")
	})

	t.Run("GetFirstDataEta_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.FirstDataEta = nil

		// Act & Assert
		assert.Nil(t, obj.GetFirstDataEta(), "getter should return nil when property is nil")
	})

	t.Run("GetFirstDataEta_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFirstDataEta() // Should return zero value
	})

	t.Run("GetCoverageExcludes", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected []string
		obj.CoverageExcludes = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCoverageExcludes(), "getter should return the property value")
	})

	t.Run("GetCoverageExcludes_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.CoverageExcludes = nil

		// Act & Assert
		assert.Nil(t, obj.GetCoverageExcludes(), "getter should return nil when property is nil")
	})

	t.Run("GetCoverageExcludes_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCoverageExcludes() // Should return zero value
	})

	t.Run("GetCostBasisClass", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *string
		obj.CostBasisClass = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCostBasisClass(), "getter should return the property value")
	})

	t.Run("GetCostBasisClass_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.CostBasisClass = nil

		// Act & Assert
		assert.Nil(t, obj.GetCostBasisClass(), "getter should return nil when property is nil")
	})

	t.Run("GetCostBasisClass_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCostBasisClass() // Should return zero value
	})

	t.Run("GetSetupScript", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected *string
		obj.SetupScript = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSetupScript(), "getter should return the property value")
	})

	t.Run("GetSetupScript_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.SetupScript = nil

		// Act & Assert
		assert.Nil(t, obj.GetSetupScript(), "getter should return nil when property is nil")
	})

	t.Run("GetSetupScript_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSetupScript() // Should return zero value
	})

	t.Run("GetEvents", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var expected []map[string]any
		obj.Events = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEvents(), "getter should return the property value")
	})

	t.Run("GetEvents_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		obj.Events = nil

		// Act & Assert
		assert.Nil(t, obj.GetEvents(), "getter should return nil when property is nil")
	})

	t.Run("GetEvents_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEvents() // Should return zero value
	})

}

func TestSettersMarkExplicitConnectionSchema(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProvider_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueProvider string

		// Act
		obj.SetProvider(fernTestValueProvider)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSource_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueSource string

		// Act
		obj.SetSource(fernTestValueSource)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDisplayName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueDisplayName string

		// Act
		obj.SetDisplayName(fernTestValueDisplayName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueStatus string

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatusReason_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueStatusReason *string

		// Act
		obj.SetStatusReason(fernTestValueStatusReason)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBillingAccountID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueBillingAccountID *string

		// Act
		obj.SetBillingAccountID(fernTestValueBillingAccountID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBillingAccountName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueBillingAccountName *string

		// Act
		obj.SetBillingAccountName(fernTestValueBillingAccountName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBilledVia_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueBilledVia *string

		// Act
		obj.SetBilledVia(fernTestValueBilledVia)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCredentialFingerprint_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueCredentialFingerprint *string

		// Act
		obj.SetCredentialFingerprint(fernTestValueCredentialFingerprint)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCredentialHint_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueCredentialHint *string

		// Act
		obj.SetCredentialHint(fernTestValueCredentialHint)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCredentialExpiresAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueCredentialExpiresAt *time.Time

		// Act
		obj.SetCredentialExpiresAt(fernTestValueCredentialExpiresAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLastSuccessAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueLastSuccessAt *time.Time

		// Act
		obj.SetLastSuccessAt(fernTestValueLastSuccessAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNextSyncAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueNextSyncAt *time.Time

		// Act
		obj.SetNextSyncAt(fernTestValueNextSyncAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBackfillCompleteAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueBackfillCompleteAt *time.Time

		// Act
		obj.SetBackfillCompleteAt(fernTestValueBackfillCompleteAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueCreatedAt *time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetConfig_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueConfig map[string]any

		// Act
		obj.SetConfig(fernTestValueConfig)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDataGrain_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueDataGrain *string

		// Act
		obj.SetDataGrain(fernTestValueDataGrain)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFirstDataEta_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueFirstDataEta *string

		// Act
		obj.SetFirstDataEta(fernTestValueFirstDataEta)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCoverageExcludes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueCoverageExcludes []string

		// Act
		obj.SetCoverageExcludes(fernTestValueCoverageExcludes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCostBasisClass_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueCostBasisClass *string

		// Act
		obj.SetCostBasisClass(fernTestValueCostBasisClass)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSetupScript_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueSetupScript *string

		// Act
		obj.SetSetupScript(fernTestValueSetupScript)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEvents_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}
		var fernTestValueEvents []map[string]any

		// Act
		obj.SetEvents(fernTestValueEvents)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingConnectionResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ConnectionResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ConnectionResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ConnectionResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingConnectionSchema(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConnectionSchema{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ConnectionSchema
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ConnectionSchema
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ConnectionSchema
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringConnectionResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ConnectionResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringConnectionSchema(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ConnectionSchema{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesConnectionResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ConnectionResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesConnectionSchema(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ConnectionSchema{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConnectionSchema
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
