// Code generated by Fern. DO NOT EDIT.

package levelfour

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/LevelFourAI/levelfour-go/internal"
	big "math/big"
	time "time"
)

var (
	createInvitationsRequestFieldInvites = big.NewInt(1 << 0)
)

type CreateInvitationsRequest struct {
	Invites []*InviteInput `json:"invites" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateInvitationsRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetInvites sets the Invites field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateInvitationsRequest) SetInvites(invites []*InviteInput) {
	c.Invites = invites
	c.require(createInvitationsRequestFieldInvites)
}

func (c *CreateInvitationsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateInvitationsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateInvitationsRequest(body)
	return nil
}

func (c *CreateInvitationsRequest) MarshalJSON() ([]byte, error) {
	type embed CreateInvitationsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createdInvitationsDataFieldItems = big.NewInt(1 << 0)
)

type CreatedInvitationsData struct {
	Items []*Invitation `json:"items" url:"items"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreatedInvitationsData) GetItems() []*Invitation {
	if c == nil {
		return nil
	}
	return c.Items
}

func (c *CreatedInvitationsData) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreatedInvitationsData) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatedInvitationsData) SetItems(items []*Invitation) {
	c.Items = items
	c.require(createdInvitationsDataFieldItems)
}

func (c *CreatedInvitationsData) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatedInvitationsData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreatedInvitationsData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatedInvitationsData) MarshalJSON() ([]byte, error) {
	type embed CreatedInvitationsData
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreatedInvitationsData) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createdInvitationsResponseFieldSuccess   = big.NewInt(1 << 0)
	createdInvitationsResponseFieldTimestamp = big.NewInt(1 << 1)
	createdInvitationsResponseFieldData      = big.NewInt(1 << 2)
)

type CreatedInvitationsResponse struct {
	Success   *bool                   `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time              `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *CreatedInvitationsData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreatedInvitationsResponse) GetSuccess() *bool {
	if c == nil {
		return nil
	}
	return c.Success
}

func (c *CreatedInvitationsResponse) GetTimestamp() *time.Time {
	if c == nil {
		return nil
	}
	return c.Timestamp
}

func (c *CreatedInvitationsResponse) GetData() *CreatedInvitationsData {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreatedInvitationsResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreatedInvitationsResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatedInvitationsResponse) SetSuccess(success *bool) {
	c.Success = success
	c.require(createdInvitationsResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatedInvitationsResponse) SetTimestamp(timestamp *time.Time) {
	c.Timestamp = timestamp
	c.require(createdInvitationsResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatedInvitationsResponse) SetData(data *CreatedInvitationsData) {
	c.Data = data
	c.require(createdInvitationsResponseFieldData)
}

func (c *CreatedInvitationsResponse) UnmarshalJSON(data []byte) error {
	type embed CreatedInvitationsResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CreatedInvitationsResponse(unmarshaler.embed)
	c.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatedInvitationsResponse) MarshalJSON() ([]byte, error) {
	type embed CreatedInvitationsResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*c),
		Timestamp: internal.NewOptionalDateTime(c.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreatedInvitationsResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	currentMemberFieldID    = big.NewInt(1 << 0)
	currentMemberFieldName  = big.NewInt(1 << 1)
	currentMemberFieldEmail = big.NewInt(1 << 2)
	currentMemberFieldRole  = big.NewInt(1 << 3)
)

type CurrentMember struct {
	ID    string            `json:"id" url:"id"`
	Name  string            `json:"name" url:"name"`
	Email string            `json:"email" url:"email"`
	Role  CurrentMemberRole `json:"role" url:"role"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CurrentMember) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CurrentMember) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CurrentMember) GetEmail() string {
	if c == nil {
		return ""
	}
	return c.Email
}

func (c *CurrentMember) GetRole() CurrentMemberRole {
	if c == nil {
		return ""
	}
	return c.Role
}

func (c *CurrentMember) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CurrentMember) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrentMember) SetID(id string) {
	c.ID = id
	c.require(currentMemberFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrentMember) SetName(name string) {
	c.Name = name
	c.require(currentMemberFieldName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrentMember) SetEmail(email string) {
	c.Email = email
	c.require(currentMemberFieldEmail)
}

// SetRole sets the Role field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrentMember) SetRole(role CurrentMemberRole) {
	c.Role = role
	c.require(currentMemberFieldRole)
}

func (c *CurrentMember) UnmarshalJSON(data []byte) error {
	type unmarshaler CurrentMember
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CurrentMember(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CurrentMember) MarshalJSON() ([]byte, error) {
	type embed CurrentMember
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CurrentMember) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	currentMemberResponseFieldSuccess   = big.NewInt(1 << 0)
	currentMemberResponseFieldTimestamp = big.NewInt(1 << 1)
	currentMemberResponseFieldData      = big.NewInt(1 << 2)
)

type CurrentMemberResponse struct {
	Success   *bool          `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time     `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *CurrentMember `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CurrentMemberResponse) GetSuccess() *bool {
	if c == nil {
		return nil
	}
	return c.Success
}

func (c *CurrentMemberResponse) GetTimestamp() *time.Time {
	if c == nil {
		return nil
	}
	return c.Timestamp
}

func (c *CurrentMemberResponse) GetData() *CurrentMember {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CurrentMemberResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CurrentMemberResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrentMemberResponse) SetSuccess(success *bool) {
	c.Success = success
	c.require(currentMemberResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrentMemberResponse) SetTimestamp(timestamp *time.Time) {
	c.Timestamp = timestamp
	c.require(currentMemberResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CurrentMemberResponse) SetData(data *CurrentMember) {
	c.Data = data
	c.require(currentMemberResponseFieldData)
}

func (c *CurrentMemberResponse) UnmarshalJSON(data []byte) error {
	type embed CurrentMemberResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CurrentMemberResponse(unmarshaler.embed)
	c.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CurrentMemberResponse) MarshalJSON() ([]byte, error) {
	type embed CurrentMemberResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*c),
		Timestamp: internal.NewOptionalDateTime(c.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CurrentMemberResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CurrentMemberRole string

const (
	CurrentMemberRoleAdmin  CurrentMemberRole = "admin"
	CurrentMemberRoleMember CurrentMemberRole = "member"
	CurrentMemberRoleViewer CurrentMemberRole = "viewer"
)

func NewCurrentMemberRoleFromString(s string) (CurrentMemberRole, error) {
	switch s {
	case "admin":
		return CurrentMemberRoleAdmin, nil
	case "member":
		return CurrentMemberRoleMember, nil
	case "viewer":
		return CurrentMemberRoleViewer, nil
	}
	var t CurrentMemberRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CurrentMemberRole) Ptr() *CurrentMemberRole {
	return &c
}

var (
	discoverabilityResponseFieldSuccess   = big.NewInt(1 << 0)
	discoverabilityResponseFieldTimestamp = big.NewInt(1 << 1)
	discoverabilityResponseFieldData      = big.NewInt(1 << 2)
)

type DiscoverabilityResponse struct {
	Success   *bool                    `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time               `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *DiscoverabilitySettings `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DiscoverabilityResponse) GetSuccess() *bool {
	if d == nil {
		return nil
	}
	return d.Success
}

func (d *DiscoverabilityResponse) GetTimestamp() *time.Time {
	if d == nil {
		return nil
	}
	return d.Timestamp
}

func (d *DiscoverabilityResponse) GetData() *DiscoverabilitySettings {
	if d == nil {
		return nil
	}
	return d.Data
}

func (d *DiscoverabilityResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DiscoverabilityResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoverabilityResponse) SetSuccess(success *bool) {
	d.Success = success
	d.require(discoverabilityResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoverabilityResponse) SetTimestamp(timestamp *time.Time) {
	d.Timestamp = timestamp
	d.require(discoverabilityResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoverabilityResponse) SetData(data *DiscoverabilitySettings) {
	d.Data = data
	d.require(discoverabilityResponseFieldData)
}

func (d *DiscoverabilityResponse) UnmarshalJSON(data []byte) error {
	type embed DiscoverabilityResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*d),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*d = DiscoverabilityResponse(unmarshaler.embed)
	d.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DiscoverabilityResponse) MarshalJSON() ([]byte, error) {
	type embed DiscoverabilityResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*d),
		Timestamp: internal.NewOptionalDateTime(d.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DiscoverabilityResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	discoverabilitySettingsFieldMode    = big.NewInt(1 << 0)
	discoverabilitySettingsFieldDomains = big.NewInt(1 << 1)
)

type DiscoverabilitySettings struct {
	Mode    DiscoverabilitySettingsMode `json:"mode" url:"mode"`
	Domains []string                    `json:"domains" url:"domains"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DiscoverabilitySettings) GetMode() DiscoverabilitySettingsMode {
	if d == nil {
		return ""
	}
	return d.Mode
}

func (d *DiscoverabilitySettings) GetDomains() []string {
	if d == nil {
		return nil
	}
	return d.Domains
}

func (d *DiscoverabilitySettings) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DiscoverabilitySettings) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetMode sets the Mode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoverabilitySettings) SetMode(mode DiscoverabilitySettingsMode) {
	d.Mode = mode
	d.require(discoverabilitySettingsFieldMode)
}

// SetDomains sets the Domains field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DiscoverabilitySettings) SetDomains(domains []string) {
	d.Domains = domains
	d.require(discoverabilitySettingsFieldDomains)
}

func (d *DiscoverabilitySettings) UnmarshalJSON(data []byte) error {
	type unmarshaler DiscoverabilitySettings
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DiscoverabilitySettings(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DiscoverabilitySettings) MarshalJSON() ([]byte, error) {
	type embed DiscoverabilitySettings
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DiscoverabilitySettings) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DiscoverabilitySettingsMode string

const (
	DiscoverabilitySettingsModeOpen          DiscoverabilitySettingsMode = "open"
	DiscoverabilitySettingsModeAdminApproval DiscoverabilitySettingsMode = "admin_approval"
	DiscoverabilitySettingsModeInviteOnly    DiscoverabilitySettingsMode = "invite_only"
)

func NewDiscoverabilitySettingsModeFromString(s string) (DiscoverabilitySettingsMode, error) {
	switch s {
	case "open":
		return DiscoverabilitySettingsModeOpen, nil
	case "admin_approval":
		return DiscoverabilitySettingsModeAdminApproval, nil
	case "invite_only":
		return DiscoverabilitySettingsModeInviteOnly, nil
	}
	var t DiscoverabilitySettingsMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DiscoverabilitySettingsMode) Ptr() *DiscoverabilitySettingsMode {
	return &d
}

var (
	invitationFieldID        = big.NewInt(1 << 0)
	invitationFieldEmail     = big.NewInt(1 << 1)
	invitationFieldRole      = big.NewInt(1 << 2)
	invitationFieldStatus    = big.NewInt(1 << 3)
	invitationFieldInvitedBy = big.NewInt(1 << 4)
	invitationFieldInvitedAt = big.NewInt(1 << 5)
)

type Invitation struct {
	ID        string         `json:"id" url:"id"`
	Email     string         `json:"email" url:"email"`
	Role      InvitationRole `json:"role" url:"role"`
	Status    *string        `json:"status,omitempty" url:"status,omitempty"`
	InvitedBy string         `json:"invited_by" url:"invited_by"`
	InvitedAt time.Time      `json:"invited_at" url:"invited_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *Invitation) GetID() string {
	if i == nil {
		return ""
	}
	return i.ID
}

func (i *Invitation) GetEmail() string {
	if i == nil {
		return ""
	}
	return i.Email
}

func (i *Invitation) GetRole() InvitationRole {
	if i == nil {
		return ""
	}
	return i.Role
}

func (i *Invitation) GetInvitedBy() string {
	if i == nil {
		return ""
	}
	return i.InvitedBy
}

func (i *Invitation) GetInvitedAt() time.Time {
	if i == nil {
		return time.Time{}
	}
	return i.InvitedAt
}

func (i *Invitation) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *Invitation) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Invitation) SetID(id string) {
	i.ID = id
	i.require(invitationFieldID)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Invitation) SetEmail(email string) {
	i.Email = email
	i.require(invitationFieldEmail)
}

// SetRole sets the Role field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Invitation) SetRole(role InvitationRole) {
	i.Role = role
	i.require(invitationFieldRole)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Invitation) SetStatus(status *string) {
	i.Status = status
	i.require(invitationFieldStatus)
}

// SetInvitedBy sets the InvitedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Invitation) SetInvitedBy(invitedBy string) {
	i.InvitedBy = invitedBy
	i.require(invitationFieldInvitedBy)
}

// SetInvitedAt sets the InvitedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *Invitation) SetInvitedAt(invitedAt time.Time) {
	i.InvitedAt = invitedAt
	i.require(invitationFieldInvitedAt)
}

func (i *Invitation) UnmarshalJSON(data []byte) error {
	type embed Invitation
	var unmarshaler = struct {
		embed
		InvitedAt *internal.DateTime `json:"invited_at"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = Invitation(unmarshaler.embed)
	i.InvitedAt = unmarshaler.InvitedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *Invitation) MarshalJSON() ([]byte, error) {
	type embed Invitation
	var marshaler = struct {
		embed
		InvitedAt *internal.DateTime `json:"invited_at"`
	}{
		embed:     embed(*i),
		InvitedAt: internal.NewDateTime(i.InvitedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *Invitation) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	invitationResponseFieldSuccess   = big.NewInt(1 << 0)
	invitationResponseFieldTimestamp = big.NewInt(1 << 1)
	invitationResponseFieldData      = big.NewInt(1 << 2)
)

type InvitationResponse struct {
	Success   *bool       `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time  `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *Invitation `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InvitationResponse) GetSuccess() *bool {
	if i == nil {
		return nil
	}
	return i.Success
}

func (i *InvitationResponse) GetTimestamp() *time.Time {
	if i == nil {
		return nil
	}
	return i.Timestamp
}

func (i *InvitationResponse) GetData() *Invitation {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *InvitationResponse) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InvitationResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvitationResponse) SetSuccess(success *bool) {
	i.Success = success
	i.require(invitationResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvitationResponse) SetTimestamp(timestamp *time.Time) {
	i.Timestamp = timestamp
	i.require(invitationResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvitationResponse) SetData(data *Invitation) {
	i.Data = data
	i.require(invitationResponseFieldData)
}

func (i *InvitationResponse) UnmarshalJSON(data []byte) error {
	type embed InvitationResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = InvitationResponse(unmarshaler.embed)
	i.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InvitationResponse) MarshalJSON() ([]byte, error) {
	type embed InvitationResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*i),
		Timestamp: internal.NewOptionalDateTime(i.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InvitationResponse) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type InvitationRole string

const (
	InvitationRoleAdmin  InvitationRole = "admin"
	InvitationRoleMember InvitationRole = "member"
	InvitationRoleViewer InvitationRole = "viewer"
)

func NewInvitationRoleFromString(s string) (InvitationRole, error) {
	switch s {
	case "admin":
		return InvitationRoleAdmin, nil
	case "member":
		return InvitationRoleMember, nil
	case "viewer":
		return InvitationRoleViewer, nil
	}
	var t InvitationRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i InvitationRole) Ptr() *InvitationRole {
	return &i
}

var (
	invitationsListDataFieldItems = big.NewInt(1 << 0)
	invitationsListDataFieldTotal = big.NewInt(1 << 1)
)

type InvitationsListData struct {
	Items []*Invitation `json:"items" url:"items"`
	Total int           `json:"total" url:"total"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InvitationsListData) GetItems() []*Invitation {
	if i == nil {
		return nil
	}
	return i.Items
}

func (i *InvitationsListData) GetTotal() int {
	if i == nil {
		return 0
	}
	return i.Total
}

func (i *InvitationsListData) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InvitationsListData) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvitationsListData) SetItems(items []*Invitation) {
	i.Items = items
	i.require(invitationsListDataFieldItems)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvitationsListData) SetTotal(total int) {
	i.Total = total
	i.require(invitationsListDataFieldTotal)
}

func (i *InvitationsListData) UnmarshalJSON(data []byte) error {
	type unmarshaler InvitationsListData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InvitationsListData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InvitationsListData) MarshalJSON() ([]byte, error) {
	type embed InvitationsListData
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InvitationsListData) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	invitationsListResponseFieldSuccess   = big.NewInt(1 << 0)
	invitationsListResponseFieldTimestamp = big.NewInt(1 << 1)
	invitationsListResponseFieldData      = big.NewInt(1 << 2)
)

type InvitationsListResponse struct {
	Success   *bool                `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time           `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *InvitationsListData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InvitationsListResponse) GetSuccess() *bool {
	if i == nil {
		return nil
	}
	return i.Success
}

func (i *InvitationsListResponse) GetTimestamp() *time.Time {
	if i == nil {
		return nil
	}
	return i.Timestamp
}

func (i *InvitationsListResponse) GetData() *InvitationsListData {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *InvitationsListResponse) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InvitationsListResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvitationsListResponse) SetSuccess(success *bool) {
	i.Success = success
	i.require(invitationsListResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvitationsListResponse) SetTimestamp(timestamp *time.Time) {
	i.Timestamp = timestamp
	i.require(invitationsListResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InvitationsListResponse) SetData(data *InvitationsListData) {
	i.Data = data
	i.require(invitationsListResponseFieldData)
}

func (i *InvitationsListResponse) UnmarshalJSON(data []byte) error {
	type embed InvitationsListResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*i),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*i = InvitationsListResponse(unmarshaler.embed)
	i.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InvitationsListResponse) MarshalJSON() ([]byte, error) {
	type embed InvitationsListResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*i),
		Timestamp: internal.NewOptionalDateTime(i.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InvitationsListResponse) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	inviteInputFieldEmail = big.NewInt(1 << 0)
	inviteInputFieldRole  = big.NewInt(1 << 1)
)

type InviteInput struct {
	Email string          `json:"email" url:"email"`
	Role  InviteInputRole `json:"role" url:"role"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InviteInput) GetEmail() string {
	if i == nil {
		return ""
	}
	return i.Email
}

func (i *InviteInput) GetRole() InviteInputRole {
	if i == nil {
		return ""
	}
	return i.Role
}

func (i *InviteInput) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InviteInput) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InviteInput) SetEmail(email string) {
	i.Email = email
	i.require(inviteInputFieldEmail)
}

// SetRole sets the Role field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InviteInput) SetRole(role InviteInputRole) {
	i.Role = role
	i.require(inviteInputFieldRole)
}

func (i *InviteInput) UnmarshalJSON(data []byte) error {
	type unmarshaler InviteInput
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InviteInput(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InviteInput) MarshalJSON() ([]byte, error) {
	type embed InviteInput
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InviteInput) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type InviteInputRole string

const (
	InviteInputRoleAdmin  InviteInputRole = "admin"
	InviteInputRoleMember InviteInputRole = "member"
	InviteInputRoleViewer InviteInputRole = "viewer"
)

func NewInviteInputRoleFromString(s string) (InviteInputRole, error) {
	switch s {
	case "admin":
		return InviteInputRoleAdmin, nil
	case "member":
		return InviteInputRoleMember, nil
	case "viewer":
		return InviteInputRoleViewer, nil
	}
	var t InviteInputRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i InviteInputRole) Ptr() *InviteInputRole {
	return &i
}

var (
	memberFieldID           = big.NewInt(1 << 0)
	memberFieldName         = big.NewInt(1 << 1)
	memberFieldEmail        = big.NewInt(1 << 2)
	memberFieldRole         = big.NewInt(1 << 3)
	memberFieldAvatarURL    = big.NewInt(1 << 4)
	memberFieldLastActiveAt = big.NewInt(1 << 5)
	memberFieldCreatedAt    = big.NewInt(1 << 6)
)

type Member struct {
	ID           string     `json:"id" url:"id"`
	Name         string     `json:"name" url:"name"`
	Email        string     `json:"email" url:"email"`
	Role         MemberRole `json:"role" url:"role"`
	AvatarURL    *string    `json:"avatar_url,omitempty" url:"avatar_url,omitempty"`
	LastActiveAt *time.Time `json:"last_active_at,omitempty" url:"last_active_at,omitempty"`
	CreatedAt    time.Time  `json:"created_at" url:"created_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *Member) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *Member) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *Member) GetEmail() string {
	if m == nil {
		return ""
	}
	return m.Email
}

func (m *Member) GetRole() MemberRole {
	if m == nil {
		return ""
	}
	return m.Role
}

func (m *Member) GetAvatarURL() *string {
	if m == nil {
		return nil
	}
	return m.AvatarURL
}

func (m *Member) GetLastActiveAt() *time.Time {
	if m == nil {
		return nil
	}
	return m.LastActiveAt
}

func (m *Member) GetCreatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.CreatedAt
}

func (m *Member) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *Member) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Member) SetID(id string) {
	m.ID = id
	m.require(memberFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Member) SetName(name string) {
	m.Name = name
	m.require(memberFieldName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Member) SetEmail(email string) {
	m.Email = email
	m.require(memberFieldEmail)
}

// SetRole sets the Role field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Member) SetRole(role MemberRole) {
	m.Role = role
	m.require(memberFieldRole)
}

// SetAvatarURL sets the AvatarURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Member) SetAvatarURL(avatarURL *string) {
	m.AvatarURL = avatarURL
	m.require(memberFieldAvatarURL)
}

// SetLastActiveAt sets the LastActiveAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Member) SetLastActiveAt(lastActiveAt *time.Time) {
	m.LastActiveAt = lastActiveAt
	m.require(memberFieldLastActiveAt)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Member) SetCreatedAt(createdAt time.Time) {
	m.CreatedAt = createdAt
	m.require(memberFieldCreatedAt)
}

func (m *Member) UnmarshalJSON(data []byte) error {
	type embed Member
	var unmarshaler = struct {
		embed
		LastActiveAt *internal.DateTime `json:"last_active_at,omitempty"`
		CreatedAt    *internal.DateTime `json:"created_at"`
	}{
		embed: embed(*m),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*m = Member(unmarshaler.embed)
	m.LastActiveAt = unmarshaler.LastActiveAt.TimePtr()
	m.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *Member) MarshalJSON() ([]byte, error) {
	type embed Member
	var marshaler = struct {
		embed
		LastActiveAt *internal.DateTime `json:"last_active_at,omitempty"`
		CreatedAt    *internal.DateTime `json:"created_at"`
	}{
		embed:        embed(*m),
		LastActiveAt: internal.NewOptionalDateTime(m.LastActiveAt),
		CreatedAt:    internal.NewDateTime(m.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *Member) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	memberResponseFieldSuccess   = big.NewInt(1 << 0)
	memberResponseFieldTimestamp = big.NewInt(1 << 1)
	memberResponseFieldData      = big.NewInt(1 << 2)
)

type MemberResponse struct {
	Success   *bool      `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *Member    `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MemberResponse) GetSuccess() *bool {
	if m == nil {
		return nil
	}
	return m.Success
}

func (m *MemberResponse) GetTimestamp() *time.Time {
	if m == nil {
		return nil
	}
	return m.Timestamp
}

func (m *MemberResponse) GetData() *Member {
	if m == nil {
		return nil
	}
	return m.Data
}

func (m *MemberResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MemberResponse) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MemberResponse) SetSuccess(success *bool) {
	m.Success = success
	m.require(memberResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MemberResponse) SetTimestamp(timestamp *time.Time) {
	m.Timestamp = timestamp
	m.require(memberResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MemberResponse) SetData(data *Member) {
	m.Data = data
	m.require(memberResponseFieldData)
}

func (m *MemberResponse) UnmarshalJSON(data []byte) error {
	type embed MemberResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*m),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*m = MemberResponse(unmarshaler.embed)
	m.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MemberResponse) MarshalJSON() ([]byte, error) {
	type embed MemberResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*m),
		Timestamp: internal.NewOptionalDateTime(m.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MemberResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MemberRole string

const (
	MemberRoleAdmin  MemberRole = "admin"
	MemberRoleMember MemberRole = "member"
	MemberRoleViewer MemberRole = "viewer"
)

func NewMemberRoleFromString(s string) (MemberRole, error) {
	switch s {
	case "admin":
		return MemberRoleAdmin, nil
	case "member":
		return MemberRoleMember, nil
	case "viewer":
		return MemberRoleViewer, nil
	}
	var t MemberRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MemberRole) Ptr() *MemberRole {
	return &m
}

var (
	membersListDataFieldItems = big.NewInt(1 << 0)
	membersListDataFieldTotal = big.NewInt(1 << 1)
)

type MembersListData struct {
	Items []*Member `json:"items" url:"items"`
	Total int       `json:"total" url:"total"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MembersListData) GetItems() []*Member {
	if m == nil {
		return nil
	}
	return m.Items
}

func (m *MembersListData) GetTotal() int {
	if m == nil {
		return 0
	}
	return m.Total
}

func (m *MembersListData) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MembersListData) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MembersListData) SetItems(items []*Member) {
	m.Items = items
	m.require(membersListDataFieldItems)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MembersListData) SetTotal(total int) {
	m.Total = total
	m.require(membersListDataFieldTotal)
}

func (m *MembersListData) UnmarshalJSON(data []byte) error {
	type unmarshaler MembersListData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MembersListData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MembersListData) MarshalJSON() ([]byte, error) {
	type embed MembersListData
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MembersListData) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	membersListResponseFieldSuccess   = big.NewInt(1 << 0)
	membersListResponseFieldTimestamp = big.NewInt(1 << 1)
	membersListResponseFieldData      = big.NewInt(1 << 2)
)

type MembersListResponse struct {
	Success   *bool            `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time       `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *MembersListData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MembersListResponse) GetSuccess() *bool {
	if m == nil {
		return nil
	}
	return m.Success
}

func (m *MembersListResponse) GetTimestamp() *time.Time {
	if m == nil {
		return nil
	}
	return m.Timestamp
}

func (m *MembersListResponse) GetData() *MembersListData {
	if m == nil {
		return nil
	}
	return m.Data
}

func (m *MembersListResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MembersListResponse) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MembersListResponse) SetSuccess(success *bool) {
	m.Success = success
	m.require(membersListResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MembersListResponse) SetTimestamp(timestamp *time.Time) {
	m.Timestamp = timestamp
	m.require(membersListResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MembersListResponse) SetData(data *MembersListData) {
	m.Data = data
	m.require(membersListResponseFieldData)
}

func (m *MembersListResponse) UnmarshalJSON(data []byte) error {
	type embed MembersListResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*m),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*m = MembersListResponse(unmarshaler.embed)
	m.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MembersListResponse) MarshalJSON() ([]byte, error) {
	type embed MembersListResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*m),
		Timestamp: internal.NewOptionalDateTime(m.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MembersListResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	removedMemberDataFieldID      = big.NewInt(1 << 0)
	removedMemberDataFieldRemoved = big.NewInt(1 << 1)
)

type RemovedMemberData struct {
	ID      string `json:"id" url:"id"`
	Removed bool   `json:"removed" url:"removed"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RemovedMemberData) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RemovedMemberData) GetRemoved() bool {
	if r == nil {
		return false
	}
	return r.Removed
}

func (r *RemovedMemberData) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RemovedMemberData) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemovedMemberData) SetID(id string) {
	r.ID = id
	r.require(removedMemberDataFieldID)
}

// SetRemoved sets the Removed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemovedMemberData) SetRemoved(removed bool) {
	r.Removed = removed
	r.require(removedMemberDataFieldRemoved)
}

func (r *RemovedMemberData) UnmarshalJSON(data []byte) error {
	type unmarshaler RemovedMemberData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RemovedMemberData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RemovedMemberData) MarshalJSON() ([]byte, error) {
	type embed RemovedMemberData
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RemovedMemberData) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	removedMemberResponseFieldSuccess   = big.NewInt(1 << 0)
	removedMemberResponseFieldTimestamp = big.NewInt(1 << 1)
	removedMemberResponseFieldData      = big.NewInt(1 << 2)
)

type RemovedMemberResponse struct {
	Success   *bool              `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time         `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *RemovedMemberData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RemovedMemberResponse) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *RemovedMemberResponse) GetTimestamp() *time.Time {
	if r == nil {
		return nil
	}
	return r.Timestamp
}

func (r *RemovedMemberResponse) GetData() *RemovedMemberData {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *RemovedMemberResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RemovedMemberResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemovedMemberResponse) SetSuccess(success *bool) {
	r.Success = success
	r.require(removedMemberResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemovedMemberResponse) SetTimestamp(timestamp *time.Time) {
	r.Timestamp = timestamp
	r.require(removedMemberResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemovedMemberResponse) SetData(data *RemovedMemberData) {
	r.Data = data
	r.require(removedMemberResponseFieldData)
}

func (r *RemovedMemberResponse) UnmarshalJSON(data []byte) error {
	type embed RemovedMemberResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RemovedMemberResponse(unmarshaler.embed)
	r.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RemovedMemberResponse) MarshalJSON() ([]byte, error) {
	type embed RemovedMemberResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*r),
		Timestamp: internal.NewOptionalDateTime(r.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RemovedMemberResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	revokedInvitationDataFieldID      = big.NewInt(1 << 0)
	revokedInvitationDataFieldRevoked = big.NewInt(1 << 1)
)

type RevokedInvitationData struct {
	ID      string `json:"id" url:"id"`
	Revoked bool   `json:"revoked" url:"revoked"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RevokedInvitationData) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RevokedInvitationData) GetRevoked() bool {
	if r == nil {
		return false
	}
	return r.Revoked
}

func (r *RevokedInvitationData) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RevokedInvitationData) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokedInvitationData) SetID(id string) {
	r.ID = id
	r.require(revokedInvitationDataFieldID)
}

// SetRevoked sets the Revoked field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokedInvitationData) SetRevoked(revoked bool) {
	r.Revoked = revoked
	r.require(revokedInvitationDataFieldRevoked)
}

func (r *RevokedInvitationData) UnmarshalJSON(data []byte) error {
	type unmarshaler RevokedInvitationData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RevokedInvitationData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RevokedInvitationData) MarshalJSON() ([]byte, error) {
	type embed RevokedInvitationData
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RevokedInvitationData) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	revokedInvitationResponseFieldSuccess   = big.NewInt(1 << 0)
	revokedInvitationResponseFieldTimestamp = big.NewInt(1 << 1)
	revokedInvitationResponseFieldData      = big.NewInt(1 << 2)
)

type RevokedInvitationResponse struct {
	Success   *bool                  `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time             `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *RevokedInvitationData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RevokedInvitationResponse) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *RevokedInvitationResponse) GetTimestamp() *time.Time {
	if r == nil {
		return nil
	}
	return r.Timestamp
}

func (r *RevokedInvitationResponse) GetData() *RevokedInvitationData {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *RevokedInvitationResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RevokedInvitationResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokedInvitationResponse) SetSuccess(success *bool) {
	r.Success = success
	r.require(revokedInvitationResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokedInvitationResponse) SetTimestamp(timestamp *time.Time) {
	r.Timestamp = timestamp
	r.require(revokedInvitationResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RevokedInvitationResponse) SetData(data *RevokedInvitationData) {
	r.Data = data
	r.require(revokedInvitationResponseFieldData)
}

func (r *RevokedInvitationResponse) UnmarshalJSON(data []byte) error {
	type embed RevokedInvitationResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RevokedInvitationResponse(unmarshaler.embed)
	r.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RevokedInvitationResponse) MarshalJSON() ([]byte, error) {
	type embed RevokedInvitationResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*r),
		Timestamp: internal.NewOptionalDateTime(r.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RevokedInvitationResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type UpdateDiscoverabilityRequestMode string

const (
	UpdateDiscoverabilityRequestModeOpen          UpdateDiscoverabilityRequestMode = "open"
	UpdateDiscoverabilityRequestModeAdminApproval UpdateDiscoverabilityRequestMode = "admin_approval"
	UpdateDiscoverabilityRequestModeInviteOnly    UpdateDiscoverabilityRequestMode = "invite_only"
)

func NewUpdateDiscoverabilityRequestModeFromString(s string) (UpdateDiscoverabilityRequestMode, error) {
	switch s {
	case "open":
		return UpdateDiscoverabilityRequestModeOpen, nil
	case "admin_approval":
		return UpdateDiscoverabilityRequestModeAdminApproval, nil
	case "invite_only":
		return UpdateDiscoverabilityRequestModeInviteOnly, nil
	}
	var t UpdateDiscoverabilityRequestMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateDiscoverabilityRequestMode) Ptr() *UpdateDiscoverabilityRequestMode {
	return &u
}

type UpdateRoleRequestRole string

const (
	UpdateRoleRequestRoleAdmin  UpdateRoleRequestRole = "admin"
	UpdateRoleRequestRoleMember UpdateRoleRequestRole = "member"
	UpdateRoleRequestRoleViewer UpdateRoleRequestRole = "viewer"
)

func NewUpdateRoleRequestRoleFromString(s string) (UpdateRoleRequestRole, error) {
	switch s {
	case "admin":
		return UpdateRoleRequestRoleAdmin, nil
	case "member":
		return UpdateRoleRequestRoleMember, nil
	case "viewer":
		return UpdateRoleRequestRoleViewer, nil
	}
	var t UpdateRoleRequestRole
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateRoleRequestRole) Ptr() *UpdateRoleRequestRole {
	return &u
}

var (
	updateDiscoverabilityRequestFieldMode    = big.NewInt(1 << 0)
	updateDiscoverabilityRequestFieldDomains = big.NewInt(1 << 1)
)

type UpdateDiscoverabilityRequest struct {
	Mode    UpdateDiscoverabilityRequestMode `json:"mode" url:"-"`
	Domains []string                         `json:"domains,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateDiscoverabilityRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetMode sets the Mode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDiscoverabilityRequest) SetMode(mode UpdateDiscoverabilityRequestMode) {
	u.Mode = mode
	u.require(updateDiscoverabilityRequestFieldMode)
}

// SetDomains sets the Domains field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateDiscoverabilityRequest) SetDomains(domains []string) {
	u.Domains = domains
	u.require(updateDiscoverabilityRequestFieldDomains)
}

func (u *UpdateDiscoverabilityRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateDiscoverabilityRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateDiscoverabilityRequest(body)
	return nil
}

func (u *UpdateDiscoverabilityRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateDiscoverabilityRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	updateRoleRequestFieldRole = big.NewInt(1 << 0)
)

type UpdateRoleRequest struct {
	Role UpdateRoleRequestRole `json:"role" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateRoleRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetRole sets the Role field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateRoleRequest) SetRole(role UpdateRoleRequestRole) {
	u.Role = role
	u.require(updateRoleRequestFieldRole)
}

func (u *UpdateRoleRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateRoleRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateRoleRequest(body)
	return nil
}

func (u *UpdateRoleRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateRoleRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
