// Code generated by Fern. DO NOT EDIT.

package levelfour

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/LevelFourAI/levelfour-go/internal"
	io "io"
	big "math/big"
	time "time"
)

var (
	addReactionRequestFieldContent = big.NewInt(1 << 0)
)

type AddReactionRequest struct {
	Content AddReactionRequestContent `json:"content" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AddReactionRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetContent sets the Content field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddReactionRequest) SetContent(content AddReactionRequestContent) {
	a.Content = content
	a.require(addReactionRequestFieldContent)
}

func (a *AddReactionRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AddReactionRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AddReactionRequest(body)
	return nil
}

func (a *AddReactionRequest) MarshalJSON() ([]byte, error) {
	type embed AddReactionRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createCommentRequestFieldBody     = big.NewInt(1 << 0)
	createCommentRequestFieldMentions = big.NewInt(1 << 1)
)

type CreateCommentRequest struct {
	// Comment body (GitHub-Flavored Markdown)
	Body     string     `json:"body" url:"-"`
	Mentions []*Mention `json:"mentions,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateCommentRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetBody sets the Body field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCommentRequest) SetBody(body string) {
	c.Body = body
	c.require(createCommentRequestFieldBody)
}

// SetMentions sets the Mentions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCommentRequest) SetMentions(mentions []*Mention) {
	c.Mentions = mentions
	c.require(createCommentRequestFieldMentions)
}

func (c *CreateCommentRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateCommentRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateCommentRequest(body)
	return nil
}

func (c *CreateCommentRequest) MarshalJSON() ([]byte, error) {
	type embed CreateCommentRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	updateCommentRequestFieldBody     = big.NewInt(1 << 0)
	updateCommentRequestFieldMentions = big.NewInt(1 << 1)
)

type UpdateCommentRequest struct {
	// Edited comment body (GitHub-Flavored Markdown)
	Body     string     `json:"body" url:"-"`
	Mentions []*Mention `json:"mentions,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateCommentRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetBody sets the Body field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCommentRequest) SetBody(body string) {
	u.Body = body
	u.require(updateCommentRequestFieldBody)
}

// SetMentions sets the Mentions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateCommentRequest) SetMentions(mentions []*Mention) {
	u.Mentions = mentions
	u.require(updateCommentRequestFieldMentions)
}

func (u *UpdateCommentRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateCommentRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateCommentRequest(body)
	return nil
}

func (u *UpdateCommentRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateCommentRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// A file uploaded for a comment. url is a stable authenticated endpoint that
// 307-redirects to a short-lived presigned S3 URL, so the bucket stays private.
var (
	attachmentDataFieldID          = big.NewInt(1 << 0)
	attachmentDataFieldURL         = big.NewInt(1 << 1)
	attachmentDataFieldFilename    = big.NewInt(1 << 2)
	attachmentDataFieldContentType = big.NewInt(1 << 3)
	attachmentDataFieldSizeBytes   = big.NewInt(1 << 4)
)

type AttachmentData struct {
	ID          string  `json:"id" url:"id"`
	URL         string  `json:"url" url:"url"`
	Filename    *string `json:"filename,omitempty" url:"filename,omitempty"`
	ContentType string  `json:"content_type" url:"content_type"`
	SizeBytes   int     `json:"size_bytes" url:"size_bytes"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AttachmentData) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AttachmentData) GetURL() string {
	if a == nil {
		return ""
	}
	return a.URL
}

func (a *AttachmentData) GetFilename() *string {
	if a == nil {
		return nil
	}
	return a.Filename
}

func (a *AttachmentData) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AttachmentData) GetSizeBytes() int {
	if a == nil {
		return 0
	}
	return a.SizeBytes
}

func (a *AttachmentData) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AttachmentData) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AttachmentData) SetID(id string) {
	a.ID = id
	a.require(attachmentDataFieldID)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AttachmentData) SetURL(url string) {
	a.URL = url
	a.require(attachmentDataFieldURL)
}

// SetFilename sets the Filename field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AttachmentData) SetFilename(filename *string) {
	a.Filename = filename
	a.require(attachmentDataFieldFilename)
}

// SetContentType sets the ContentType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AttachmentData) SetContentType(contentType string) {
	a.ContentType = contentType
	a.require(attachmentDataFieldContentType)
}

// SetSizeBytes sets the SizeBytes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AttachmentData) SetSizeBytes(sizeBytes int) {
	a.SizeBytes = sizeBytes
	a.require(attachmentDataFieldSizeBytes)
}

func (a *AttachmentData) UnmarshalJSON(data []byte) error {
	type unmarshaler AttachmentData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AttachmentData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AttachmentData) MarshalJSON() ([]byte, error) {
	type embed AttachmentData
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AttachmentData) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	attachmentResponseFieldSuccess   = big.NewInt(1 << 0)
	attachmentResponseFieldTimestamp = big.NewInt(1 << 1)
	attachmentResponseFieldData      = big.NewInt(1 << 2)
)

type AttachmentResponse struct {
	Success   *bool           `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time      `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *AttachmentData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AttachmentResponse) GetSuccess() *bool {
	if a == nil {
		return nil
	}
	return a.Success
}

func (a *AttachmentResponse) GetTimestamp() *time.Time {
	if a == nil {
		return nil
	}
	return a.Timestamp
}

func (a *AttachmentResponse) GetData() *AttachmentData {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *AttachmentResponse) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AttachmentResponse) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AttachmentResponse) SetSuccess(success *bool) {
	a.Success = success
	a.require(attachmentResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AttachmentResponse) SetTimestamp(timestamp *time.Time) {
	a.Timestamp = timestamp
	a.require(attachmentResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AttachmentResponse) SetData(data *AttachmentData) {
	a.Data = data
	a.require(attachmentResponseFieldData)
}

func (a *AttachmentResponse) UnmarshalJSON(data []byte) error {
	type embed AttachmentResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*a),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*a = AttachmentResponse(unmarshaler.embed)
	a.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AttachmentResponse) MarshalJSON() ([]byte, error) {
	type embed AttachmentResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*a),
		Timestamp: internal.NewOptionalDateTime(a.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AttachmentResponse) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// A non-view audit event (decision, terms, method set) surfaced inline in the feed.
var (
	auditEventFieldID         = big.NewInt(1 << 0)
	auditEventFieldEventType  = big.NewInt(1 << 1)
	auditEventFieldUser       = big.NewInt(1 << 2)
	auditEventFieldChannel    = big.NewInt(1 << 3)
	auditEventFieldOccurredAt = big.NewInt(1 << 4)
	auditEventFieldMetadata   = big.NewInt(1 << 5)
)

type AuditEvent struct {
	ID         string         `json:"id" url:"id"`
	EventType  string         `json:"event_type" url:"event_type"`
	User       *TimelineUser  `json:"user" url:"user"`
	Channel    string         `json:"channel" url:"channel"`
	OccurredAt string         `json:"occurred_at" url:"occurred_at"`
	Metadata   map[string]any `json:"metadata,omitempty" url:"metadata,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuditEvent) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AuditEvent) GetEventType() string {
	if a == nil {
		return ""
	}
	return a.EventType
}

func (a *AuditEvent) GetUser() *TimelineUser {
	if a == nil {
		return nil
	}
	return a.User
}

func (a *AuditEvent) GetChannel() string {
	if a == nil {
		return ""
	}
	return a.Channel
}

func (a *AuditEvent) GetOccurredAt() string {
	if a == nil {
		return ""
	}
	return a.OccurredAt
}

func (a *AuditEvent) GetMetadata() map[string]any {
	if a == nil {
		return nil
	}
	return a.Metadata
}

func (a *AuditEvent) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AuditEvent) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditEvent) SetID(id string) {
	a.ID = id
	a.require(auditEventFieldID)
}

// SetEventType sets the EventType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditEvent) SetEventType(eventType string) {
	a.EventType = eventType
	a.require(auditEventFieldEventType)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditEvent) SetUser(user *TimelineUser) {
	a.User = user
	a.require(auditEventFieldUser)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditEvent) SetChannel(channel string) {
	a.Channel = channel
	a.require(auditEventFieldChannel)
}

// SetOccurredAt sets the OccurredAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditEvent) SetOccurredAt(occurredAt string) {
	a.OccurredAt = occurredAt
	a.require(auditEventFieldOccurredAt)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditEvent) SetMetadata(metadata map[string]any) {
	a.Metadata = metadata
	a.require(auditEventFieldMetadata)
}

func (a *AuditEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler AuditEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuditEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuditEvent) MarshalJSON() ([]byte, error) {
	type embed AuditEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AuditEvent) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// A user-authored comment. body is GitHub-Flavored Markdown with inline @mentions.
var (
	commentFieldID        = big.NewInt(1 << 0)
	commentFieldAuthor    = big.NewInt(1 << 1)
	commentFieldBody      = big.NewInt(1 << 2)
	commentFieldMentions  = big.NewInt(1 << 3)
	commentFieldCreatedAt = big.NewInt(1 << 4)
	commentFieldEdited    = big.NewInt(1 << 5)
	commentFieldReactions = big.NewInt(1 << 6)
)

type Comment struct {
	ID        string           `json:"id" url:"id"`
	Author    *TimelineUser    `json:"author" url:"author"`
	Body      string           `json:"body" url:"body"`
	Mentions  []*Mention       `json:"mentions,omitempty" url:"mentions,omitempty"`
	CreatedAt string           `json:"created_at" url:"created_at"`
	Edited    bool             `json:"edited" url:"edited"`
	Reactions []*ReactionGroup `json:"reactions,omitempty" url:"reactions,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *Comment) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *Comment) GetAuthor() *TimelineUser {
	if c == nil {
		return nil
	}
	return c.Author
}

func (c *Comment) GetBody() string {
	if c == nil {
		return ""
	}
	return c.Body
}

func (c *Comment) GetMentions() []*Mention {
	if c == nil {
		return nil
	}
	return c.Mentions
}

func (c *Comment) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *Comment) GetEdited() bool {
	if c == nil {
		return false
	}
	return c.Edited
}

func (c *Comment) GetReactions() []*ReactionGroup {
	if c == nil {
		return nil
	}
	return c.Reactions
}

func (c *Comment) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *Comment) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Comment) SetID(id string) {
	c.ID = id
	c.require(commentFieldID)
}

// SetAuthor sets the Author field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Comment) SetAuthor(author *TimelineUser) {
	c.Author = author
	c.require(commentFieldAuthor)
}

// SetBody sets the Body field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Comment) SetBody(body string) {
	c.Body = body
	c.require(commentFieldBody)
}

// SetMentions sets the Mentions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Comment) SetMentions(mentions []*Mention) {
	c.Mentions = mentions
	c.require(commentFieldMentions)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Comment) SetCreatedAt(createdAt string) {
	c.CreatedAt = createdAt
	c.require(commentFieldCreatedAt)
}

// SetEdited sets the Edited field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Comment) SetEdited(edited bool) {
	c.Edited = edited
	c.require(commentFieldEdited)
}

// SetReactions sets the Reactions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Comment) SetReactions(reactions []*ReactionGroup) {
	c.Reactions = reactions
	c.require(commentFieldReactions)
}

func (c *Comment) UnmarshalJSON(data []byte) error {
	type unmarshaler Comment
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = Comment(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *Comment) MarshalJSON() ([]byte, error) {
	type embed Comment
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *Comment) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	commentResponseFieldSuccess   = big.NewInt(1 << 0)
	commentResponseFieldTimestamp = big.NewInt(1 << 1)
	commentResponseFieldData      = big.NewInt(1 << 2)
)

type CommentResponse struct {
	Success   *bool      `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *Comment   `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CommentResponse) GetSuccess() *bool {
	if c == nil {
		return nil
	}
	return c.Success
}

func (c *CommentResponse) GetTimestamp() *time.Time {
	if c == nil {
		return nil
	}
	return c.Timestamp
}

func (c *CommentResponse) GetData() *Comment {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CommentResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CommentResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommentResponse) SetSuccess(success *bool) {
	c.Success = success
	c.require(commentResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommentResponse) SetTimestamp(timestamp *time.Time) {
	c.Timestamp = timestamp
	c.require(commentResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CommentResponse) SetData(data *Comment) {
	c.Data = data
	c.require(commentResponseFieldData)
}

func (c *CommentResponse) UnmarshalJSON(data []byte) error {
	type embed CommentResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CommentResponse(unmarshaler.embed)
	c.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CommentResponse) MarshalJSON() ([]byte, error) {
	type embed CommentResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*c),
		Timestamp: internal.NewOptionalDateTime(c.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CommentResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// One credential's reads of this recommendation, rolled up.
//
// Separate from `views` because a credential is not a person: mixed in, every application
// collapsed into a single nameless face counted as a colleague.
//
// `label` is None when there is no name worth showing (unverified client, swept
// credential); the dashboard renders `kind` then. Facts only, never display copy: i18n
// lives entirely in the dashboard.
var (
	machineAccessFieldID           = big.NewInt(1 << 0)
	machineAccessFieldKind         = big.NewInt(1 << 1)
	machineAccessFieldLabel        = big.NewInt(1 << 2)
	machineAccessFieldChannel      = big.NewInt(1 << 3)
	machineAccessFieldCount        = big.NewInt(1 << 4)
	machineAccessFieldLastAccessAt = big.NewInt(1 << 5)
)

type MachineAccess struct {
	ID           string            `json:"id" url:"id"`
	Kind         MachineAccessKind `json:"kind" url:"kind"`
	Label        *string           `json:"label,omitempty" url:"label,omitempty"`
	Channel      string            `json:"channel" url:"channel"`
	Count        int               `json:"count" url:"count"`
	LastAccessAt string            `json:"last_access_at" url:"last_access_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MachineAccess) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *MachineAccess) GetKind() MachineAccessKind {
	if m == nil {
		return ""
	}
	return m.Kind
}

func (m *MachineAccess) GetLabel() *string {
	if m == nil {
		return nil
	}
	return m.Label
}

func (m *MachineAccess) GetChannel() string {
	if m == nil {
		return ""
	}
	return m.Channel
}

func (m *MachineAccess) GetCount() int {
	if m == nil {
		return 0
	}
	return m.Count
}

func (m *MachineAccess) GetLastAccessAt() string {
	if m == nil {
		return ""
	}
	return m.LastAccessAt
}

func (m *MachineAccess) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MachineAccess) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MachineAccess) SetID(id string) {
	m.ID = id
	m.require(machineAccessFieldID)
}

// SetKind sets the Kind field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MachineAccess) SetKind(kind MachineAccessKind) {
	m.Kind = kind
	m.require(machineAccessFieldKind)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MachineAccess) SetLabel(label *string) {
	m.Label = label
	m.require(machineAccessFieldLabel)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MachineAccess) SetChannel(channel string) {
	m.Channel = channel
	m.require(machineAccessFieldChannel)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MachineAccess) SetCount(count int) {
	m.Count = count
	m.require(machineAccessFieldCount)
}

// SetLastAccessAt sets the LastAccessAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MachineAccess) SetLastAccessAt(lastAccessAt string) {
	m.LastAccessAt = lastAccessAt
	m.require(machineAccessFieldLastAccessAt)
}

func (m *MachineAccess) UnmarshalJSON(data []byte) error {
	type unmarshaler MachineAccess
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MachineAccess(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MachineAccess) MarshalJSON() ([]byte, error) {
	type embed MachineAccess
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MachineAccess) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MachineAccessKind string

const (
	MachineAccessKindAPIKey       MachineAccessKind = "api_key"
	MachineAccessKindConnectedApp MachineAccessKind = "connected_app"
	MachineAccessKindUnattributed MachineAccessKind = "unattributed"
)

func NewMachineAccessKindFromString(s string) (MachineAccessKind, error) {
	switch s {
	case "api_key":
		return MachineAccessKindAPIKey, nil
	case "connected_app":
		return MachineAccessKindConnectedApp, nil
	case "unattributed":
		return MachineAccessKindUnattributed, nil
	}
	var t MachineAccessKind
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MachineAccessKind) Ptr() *MachineAccessKind {
	return &m
}

// A resolved @mention inside a comment body.
var (
	mentionFieldID   = big.NewInt(1 << 0)
	mentionFieldName = big.NewInt(1 << 1)
)

type Mention struct {
	ID   string `json:"id" url:"id"`
	Name string `json:"name" url:"name"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *Mention) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *Mention) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *Mention) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *Mention) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Mention) SetID(id string) {
	m.ID = id
	m.require(mentionFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Mention) SetName(name string) {
	m.Name = name
	m.require(mentionFieldName)
}

func (m *Mention) UnmarshalJSON(data []byte) error {
	type unmarshaler Mention
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = Mention(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *Mention) MarshalJSON() ([]byte, error) {
	type embed Mention
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *Mention) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

// Reactions of one emoji on a comment, grouped for the requesting user.
var (
	reactionGroupFieldContent  = big.NewInt(1 << 0)
	reactionGroupFieldCount    = big.NewInt(1 << 1)
	reactionGroupFieldReacted  = big.NewInt(1 << 2)
	reactionGroupFieldReactors = big.NewInt(1 << 3)
)

type ReactionGroup struct {
	Content ReactionGroupContent `json:"content" url:"content"`
	Count   int                  `json:"count" url:"count"`
	// Whether the requesting user reacted with this emoji
	Reacted bool `json:"reacted" url:"reacted"`
	// Display names of everyone who reacted with this emoji, for the hover tooltip
	Reactors []string `json:"reactors,omitempty" url:"reactors,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReactionGroup) GetContent() ReactionGroupContent {
	if r == nil {
		return ""
	}
	return r.Content
}

func (r *ReactionGroup) GetCount() int {
	if r == nil {
		return 0
	}
	return r.Count
}

func (r *ReactionGroup) GetReacted() bool {
	if r == nil {
		return false
	}
	return r.Reacted
}

func (r *ReactionGroup) GetReactors() []string {
	if r == nil {
		return nil
	}
	return r.Reactors
}

func (r *ReactionGroup) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReactionGroup) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetContent sets the Content field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReactionGroup) SetContent(content ReactionGroupContent) {
	r.Content = content
	r.require(reactionGroupFieldContent)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReactionGroup) SetCount(count int) {
	r.Count = count
	r.require(reactionGroupFieldCount)
}

// SetReacted sets the Reacted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReactionGroup) SetReacted(reacted bool) {
	r.Reacted = reacted
	r.require(reactionGroupFieldReacted)
}

// SetReactors sets the Reactors field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReactionGroup) SetReactors(reactors []string) {
	r.Reactors = reactors
	r.require(reactionGroupFieldReactors)
}

func (r *ReactionGroup) UnmarshalJSON(data []byte) error {
	type unmarshaler ReactionGroup
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReactionGroup(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReactionGroup) MarshalJSON() ([]byte, error) {
	type embed ReactionGroup
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReactionGroup) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type ReactionGroupContent string

const (
	ReactionGroupContentPlusOne  ReactionGroupContent = "+1"
	ReactionGroupContentMinusOne ReactionGroupContent = "-1"
	ReactionGroupContentLaugh    ReactionGroupContent = "laugh"
	ReactionGroupContentHooray   ReactionGroupContent = "hooray"
	ReactionGroupContentConfused ReactionGroupContent = "confused"
	ReactionGroupContentHeart    ReactionGroupContent = "heart"
	ReactionGroupContentRocket   ReactionGroupContent = "rocket"
	ReactionGroupContentEyes     ReactionGroupContent = "eyes"
)

func NewReactionGroupContentFromString(s string) (ReactionGroupContent, error) {
	switch s {
	case "+1":
		return ReactionGroupContentPlusOne, nil
	case "-1":
		return ReactionGroupContentMinusOne, nil
	case "laugh":
		return ReactionGroupContentLaugh, nil
	case "hooray":
		return ReactionGroupContentHooray, nil
	case "confused":
		return ReactionGroupContentConfused, nil
	case "heart":
		return ReactionGroupContentHeart, nil
	case "rocket":
		return ReactionGroupContentRocket, nil
	case "eyes":
		return ReactionGroupContentEyes, nil
	}
	var t ReactionGroupContent
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r ReactionGroupContent) Ptr() *ReactionGroupContent {
	return &r
}

var (
	timelineAckFieldOk = big.NewInt(1 << 0)
)

type TimelineAck struct {
	Ok *bool `json:"ok,omitempty" url:"ok,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TimelineAck) GetOk() *bool {
	if t == nil {
		return nil
	}
	return t.Ok
}

func (t *TimelineAck) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TimelineAck) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetOk sets the Ok field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineAck) SetOk(ok *bool) {
	t.Ok = ok
	t.require(timelineAckFieldOk)
}

func (t *TimelineAck) UnmarshalJSON(data []byte) error {
	type unmarshaler TimelineAck
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TimelineAck(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TimelineAck) MarshalJSON() ([]byte, error) {
	type embed TimelineAck
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TimelineAck) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	timelineAckResponseFieldSuccess   = big.NewInt(1 << 0)
	timelineAckResponseFieldTimestamp = big.NewInt(1 << 1)
	timelineAckResponseFieldData      = big.NewInt(1 << 2)
)

type TimelineAckResponse struct {
	Success   *bool        `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time   `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *TimelineAck `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TimelineAckResponse) GetSuccess() *bool {
	if t == nil {
		return nil
	}
	return t.Success
}

func (t *TimelineAckResponse) GetTimestamp() *time.Time {
	if t == nil {
		return nil
	}
	return t.Timestamp
}

func (t *TimelineAckResponse) GetData() *TimelineAck {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TimelineAckResponse) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TimelineAckResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineAckResponse) SetSuccess(success *bool) {
	t.Success = success
	t.require(timelineAckResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineAckResponse) SetTimestamp(timestamp *time.Time) {
	t.Timestamp = timestamp
	t.require(timelineAckResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineAckResponse) SetData(data *TimelineAck) {
	t.Data = data
	t.require(timelineAckResponseFieldData)
}

func (t *TimelineAckResponse) UnmarshalJSON(data []byte) error {
	type embed TimelineAckResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TimelineAckResponse(unmarshaler.embed)
	t.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TimelineAckResponse) MarshalJSON() ([]byte, error) {
	type embed TimelineAckResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*t),
		Timestamp: internal.NewOptionalDateTime(t.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TimelineAckResponse) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// The full activity thread for one recommendation: views, comments, and the
// decision audit log, each an independent stream the frontend interleaves.
var (
	timelineDataFieldViews         = big.NewInt(1 << 0)
	timelineDataFieldComments      = big.NewInt(1 << 1)
	timelineDataFieldEvents        = big.NewInt(1 << 2)
	timelineDataFieldMachineAccess = big.NewInt(1 << 3)
)

type TimelineData struct {
	Views         []*ViewEvent     `json:"views,omitempty" url:"views,omitempty"`
	Comments      []*Comment       `json:"comments,omitempty" url:"comments,omitempty"`
	Events        []*AuditEvent    `json:"events,omitempty" url:"events,omitempty"`
	MachineAccess []*MachineAccess `json:"machine_access,omitempty" url:"machine_access,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TimelineData) GetViews() []*ViewEvent {
	if t == nil {
		return nil
	}
	return t.Views
}

func (t *TimelineData) GetComments() []*Comment {
	if t == nil {
		return nil
	}
	return t.Comments
}

func (t *TimelineData) GetEvents() []*AuditEvent {
	if t == nil {
		return nil
	}
	return t.Events
}

func (t *TimelineData) GetMachineAccess() []*MachineAccess {
	if t == nil {
		return nil
	}
	return t.MachineAccess
}

func (t *TimelineData) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TimelineData) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetViews sets the Views field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineData) SetViews(views []*ViewEvent) {
	t.Views = views
	t.require(timelineDataFieldViews)
}

// SetComments sets the Comments field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineData) SetComments(comments []*Comment) {
	t.Comments = comments
	t.require(timelineDataFieldComments)
}

// SetEvents sets the Events field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineData) SetEvents(events []*AuditEvent) {
	t.Events = events
	t.require(timelineDataFieldEvents)
}

// SetMachineAccess sets the MachineAccess field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineData) SetMachineAccess(machineAccess []*MachineAccess) {
	t.MachineAccess = machineAccess
	t.require(timelineDataFieldMachineAccess)
}

func (t *TimelineData) UnmarshalJSON(data []byte) error {
	type unmarshaler TimelineData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TimelineData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TimelineData) MarshalJSON() ([]byte, error) {
	type embed TimelineData
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TimelineData) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	timelineResponseFieldSuccess   = big.NewInt(1 << 0)
	timelineResponseFieldTimestamp = big.NewInt(1 << 1)
	timelineResponseFieldData      = big.NewInt(1 << 2)
)

type TimelineResponse struct {
	Success   *bool         `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time    `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *TimelineData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TimelineResponse) GetSuccess() *bool {
	if t == nil {
		return nil
	}
	return t.Success
}

func (t *TimelineResponse) GetTimestamp() *time.Time {
	if t == nil {
		return nil
	}
	return t.Timestamp
}

func (t *TimelineResponse) GetData() *TimelineData {
	if t == nil {
		return nil
	}
	return t.Data
}

func (t *TimelineResponse) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TimelineResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineResponse) SetSuccess(success *bool) {
	t.Success = success
	t.require(timelineResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineResponse) SetTimestamp(timestamp *time.Time) {
	t.Timestamp = timestamp
	t.require(timelineResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineResponse) SetData(data *TimelineData) {
	t.Data = data
	t.require(timelineResponseFieldData)
}

func (t *TimelineResponse) UnmarshalJSON(data []byte) error {
	type embed TimelineResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TimelineResponse(unmarshaler.embed)
	t.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TimelineResponse) MarshalJSON() ([]byte, error) {
	type embed TimelineResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*t),
		Timestamp: internal.NewOptionalDateTime(t.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TimelineResponse) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// A resolved actor on the timeline (author of a comment, viewer, or audit actor).
var (
	timelineUserFieldID        = big.NewInt(1 << 0)
	timelineUserFieldName      = big.NewInt(1 << 1)
	timelineUserFieldEmail     = big.NewInt(1 << 2)
	timelineUserFieldAvatarURL = big.NewInt(1 << 3)
)

type TimelineUser struct {
	ID        string  `json:"id" url:"id"`
	Name      string  `json:"name" url:"name"`
	Email     string  `json:"email" url:"email"`
	AvatarURL *string `json:"avatar_url,omitempty" url:"avatar_url,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TimelineUser) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TimelineUser) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TimelineUser) GetEmail() string {
	if t == nil {
		return ""
	}
	return t.Email
}

func (t *TimelineUser) GetAvatarURL() *string {
	if t == nil {
		return nil
	}
	return t.AvatarURL
}

func (t *TimelineUser) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TimelineUser) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineUser) SetID(id string) {
	t.ID = id
	t.require(timelineUserFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineUser) SetName(name string) {
	t.Name = name
	t.require(timelineUserFieldName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineUser) SetEmail(email string) {
	t.Email = email
	t.require(timelineUserFieldEmail)
}

// SetAvatarURL sets the AvatarURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimelineUser) SetAvatarURL(avatarURL *string) {
	t.AvatarURL = avatarURL
	t.require(timelineUserFieldAvatarURL)
}

func (t *TimelineUser) UnmarshalJSON(data []byte) error {
	type unmarshaler TimelineUser
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TimelineUser(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TimelineUser) MarshalJSON() ([]byte, error) {
	type embed TimelineUser
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TimelineUser) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// One recorded drawer open. Stored individually; the frontend groups repeated
// views by the same user for display.
var (
	viewEventFieldID       = big.NewInt(1 << 0)
	viewEventFieldUser     = big.NewInt(1 << 1)
	viewEventFieldViewedAt = big.NewInt(1 << 2)
)

type ViewEvent struct {
	ID       string        `json:"id" url:"id"`
	User     *TimelineUser `json:"user" url:"user"`
	ViewedAt string        `json:"viewed_at" url:"viewed_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *ViewEvent) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *ViewEvent) GetUser() *TimelineUser {
	if v == nil {
		return nil
	}
	return v.User
}

func (v *ViewEvent) GetViewedAt() string {
	if v == nil {
		return ""
	}
	return v.ViewedAt
}

func (v *ViewEvent) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *ViewEvent) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ViewEvent) SetID(id string) {
	v.ID = id
	v.require(viewEventFieldID)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ViewEvent) SetUser(user *TimelineUser) {
	v.User = user
	v.require(viewEventFieldUser)
}

// SetViewedAt sets the ViewedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ViewEvent) SetViewedAt(viewedAt string) {
	v.ViewedAt = viewedAt
	v.require(viewEventFieldViewedAt)
}

func (v *ViewEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler ViewEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = ViewEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *ViewEvent) MarshalJSON() ([]byte, error) {
	type embed ViewEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *ViewEvent) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

type AddReactionRequestContent string

const (
	AddReactionRequestContentPlusOne  AddReactionRequestContent = "+1"
	AddReactionRequestContentMinusOne AddReactionRequestContent = "-1"
	AddReactionRequestContentLaugh    AddReactionRequestContent = "laugh"
	AddReactionRequestContentHooray   AddReactionRequestContent = "hooray"
	AddReactionRequestContentConfused AddReactionRequestContent = "confused"
	AddReactionRequestContentHeart    AddReactionRequestContent = "heart"
	AddReactionRequestContentRocket   AddReactionRequestContent = "rocket"
	AddReactionRequestContentEyes     AddReactionRequestContent = "eyes"
)

func NewAddReactionRequestContentFromString(s string) (AddReactionRequestContent, error) {
	switch s {
	case "+1":
		return AddReactionRequestContentPlusOne, nil
	case "-1":
		return AddReactionRequestContentMinusOne, nil
	case "laugh":
		return AddReactionRequestContentLaugh, nil
	case "hooray":
		return AddReactionRequestContentHooray, nil
	case "confused":
		return AddReactionRequestContentConfused, nil
	case "heart":
		return AddReactionRequestContentHeart, nil
	case "rocket":
		return AddReactionRequestContentRocket, nil
	case "eyes":
		return AddReactionRequestContentEyes, nil
	}
	var t AddReactionRequestContent
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AddReactionRequestContent) Ptr() *AddReactionRequestContent {
	return &a
}

type BodyUploadAttachmentAPIV1RecommendationsRecommendationIDAttachmentsPost struct {
	File io.Reader `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *BodyUploadAttachmentAPIV1RecommendationsRecommendationIDAttachmentsPost) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}
