// Code generated by Fern. DO NOT EDIT.

package levelfour

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/LevelFourAI/levelfour-go/internal"
	big "math/big"
	time "time"
)

var (
	bindReposRequestFieldInstallationID = big.NewInt(1 << 0)
	bindReposRequestFieldRepos          = big.NewInt(1 << 1)
)

type BindReposRequest struct {
	// GitHub App installation id that grants access to the repos
	InstallationID int `json:"installation_id" url:"-"`
	// Full names (owner/name) to bind to this recommendation
	Repos []string `json:"repos" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *BindReposRequest) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetInstallationID sets the InstallationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BindReposRequest) SetInstallationID(installationID int) {
	b.InstallationID = installationID
	b.require(bindReposRequestFieldInstallationID)
}

// SetRepos sets the Repos field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BindReposRequest) SetRepos(repos []string) {
	b.Repos = repos
	b.require(bindReposRequestFieldRepos)
}

func (b *BindReposRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler BindReposRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*b = BindReposRequest(body)
	return nil
}

func (b *BindReposRequest) MarshalJSON() ([]byte, error) {
	type embed BindReposRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	listAvailableReposAPIV1RepoBindingInstallationsInstallationIDReposGetRequestFieldQuery = big.NewInt(1 << 0)
)

type ListAvailableReposAPIV1RepoBindingInstallationsInstallationIDReposGetRequest struct {
	// Case-insensitive substring of the repository name
	Query *string `json:"-" url:"query,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListAvailableReposAPIV1RepoBindingInstallationsInstallationIDReposGetRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListAvailableReposAPIV1RepoBindingInstallationsInstallationIDReposGetRequest) SetQuery(query *string) {
	l.Query = query
	l.require(listAvailableReposAPIV1RepoBindingInstallationsInstallationIDReposGetRequestFieldQuery)
}

var (
	availableReposDataFieldInstallationID = big.NewInt(1 << 0)
	availableReposDataFieldRepos          = big.NewInt(1 << 1)
)

type AvailableReposData struct {
	InstallationID int      `json:"installation_id" url:"installation_id"`
	Repos          []string `json:"repos,omitempty" url:"repos,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AvailableReposData) GetInstallationID() int {
	if a == nil {
		return 0
	}
	return a.InstallationID
}

func (a *AvailableReposData) GetRepos() []string {
	if a == nil {
		return nil
	}
	return a.Repos
}

func (a *AvailableReposData) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AvailableReposData) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetInstallationID sets the InstallationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AvailableReposData) SetInstallationID(installationID int) {
	a.InstallationID = installationID
	a.require(availableReposDataFieldInstallationID)
}

// SetRepos sets the Repos field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AvailableReposData) SetRepos(repos []string) {
	a.Repos = repos
	a.require(availableReposDataFieldRepos)
}

func (a *AvailableReposData) UnmarshalJSON(data []byte) error {
	type unmarshaler AvailableReposData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AvailableReposData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AvailableReposData) MarshalJSON() ([]byte, error) {
	type embed AvailableReposData
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AvailableReposData) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	availableReposResponseFieldSuccess   = big.NewInt(1 << 0)
	availableReposResponseFieldTimestamp = big.NewInt(1 << 1)
	availableReposResponseFieldData      = big.NewInt(1 << 2)
)

type AvailableReposResponse struct {
	Success   *bool               `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time          `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *AvailableReposData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AvailableReposResponse) GetSuccess() *bool {
	if a == nil {
		return nil
	}
	return a.Success
}

func (a *AvailableReposResponse) GetTimestamp() *time.Time {
	if a == nil {
		return nil
	}
	return a.Timestamp
}

func (a *AvailableReposResponse) GetData() *AvailableReposData {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *AvailableReposResponse) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AvailableReposResponse) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AvailableReposResponse) SetSuccess(success *bool) {
	a.Success = success
	a.require(availableReposResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AvailableReposResponse) SetTimestamp(timestamp *time.Time) {
	a.Timestamp = timestamp
	a.require(availableReposResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AvailableReposResponse) SetData(data *AvailableReposData) {
	a.Data = data
	a.require(availableReposResponseFieldData)
}

func (a *AvailableReposResponse) UnmarshalJSON(data []byte) error {
	type embed AvailableReposResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*a),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*a = AvailableReposResponse(unmarshaler.embed)
	a.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AvailableReposResponse) MarshalJSON() ([]byte, error) {
	type embed AvailableReposResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*a),
		Timestamp: internal.NewOptionalDateTime(a.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AvailableReposResponse) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	repoTargetFieldRepoFullName   = big.NewInt(1 << 0)
	repoTargetFieldInstallationID = big.NewInt(1 << 1)
	repoTargetFieldPrURL          = big.NewInt(1 << 2)
	repoTargetFieldPrNumber       = big.NewInt(1 << 3)
	repoTargetFieldPrStatus       = big.NewInt(1 << 4)
	repoTargetFieldOpenedAt       = big.NewInt(1 << 5)
	repoTargetFieldErrorMessage   = big.NewInt(1 << 6)
)

type RepoTarget struct {
	// Full name (owner/name) of the bound repository
	RepoFullName string `json:"repo_full_name" url:"repo_full_name"`
	// GitHub App installation id for this repository
	InstallationID int        `json:"installation_id" url:"installation_id"`
	PrURL          *string    `json:"pr_url,omitempty" url:"pr_url,omitempty"`
	PrNumber       *int       `json:"pr_number,omitempty" url:"pr_number,omitempty"`
	PrStatus       *string    `json:"pr_status,omitempty" url:"pr_status,omitempty"`
	OpenedAt       *time.Time `json:"opened_at,omitempty" url:"opened_at,omitempty"`
	ErrorMessage   *string    `json:"error_message,omitempty" url:"error_message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RepoTarget) GetRepoFullName() string {
	if r == nil {
		return ""
	}
	return r.RepoFullName
}

func (r *RepoTarget) GetInstallationID() int {
	if r == nil {
		return 0
	}
	return r.InstallationID
}

func (r *RepoTarget) GetPrURL() *string {
	if r == nil {
		return nil
	}
	return r.PrURL
}

func (r *RepoTarget) GetPrNumber() *int {
	if r == nil {
		return nil
	}
	return r.PrNumber
}

func (r *RepoTarget) GetPrStatus() *string {
	if r == nil {
		return nil
	}
	return r.PrStatus
}

func (r *RepoTarget) GetOpenedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.OpenedAt
}

func (r *RepoTarget) GetErrorMessage() *string {
	if r == nil {
		return nil
	}
	return r.ErrorMessage
}

func (r *RepoTarget) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RepoTarget) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRepoFullName sets the RepoFullName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTarget) SetRepoFullName(repoFullName string) {
	r.RepoFullName = repoFullName
	r.require(repoTargetFieldRepoFullName)
}

// SetInstallationID sets the InstallationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTarget) SetInstallationID(installationID int) {
	r.InstallationID = installationID
	r.require(repoTargetFieldInstallationID)
}

// SetPrURL sets the PrURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTarget) SetPrURL(prURL *string) {
	r.PrURL = prURL
	r.require(repoTargetFieldPrURL)
}

// SetPrNumber sets the PrNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTarget) SetPrNumber(prNumber *int) {
	r.PrNumber = prNumber
	r.require(repoTargetFieldPrNumber)
}

// SetPrStatus sets the PrStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTarget) SetPrStatus(prStatus *string) {
	r.PrStatus = prStatus
	r.require(repoTargetFieldPrStatus)
}

// SetOpenedAt sets the OpenedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTarget) SetOpenedAt(openedAt *time.Time) {
	r.OpenedAt = openedAt
	r.require(repoTargetFieldOpenedAt)
}

// SetErrorMessage sets the ErrorMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTarget) SetErrorMessage(errorMessage *string) {
	r.ErrorMessage = errorMessage
	r.require(repoTargetFieldErrorMessage)
}

func (r *RepoTarget) UnmarshalJSON(data []byte) error {
	type embed RepoTarget
	var unmarshaler = struct {
		embed
		OpenedAt *internal.DateTime `json:"opened_at,omitempty"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RepoTarget(unmarshaler.embed)
	r.OpenedAt = unmarshaler.OpenedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RepoTarget) MarshalJSON() ([]byte, error) {
	type embed RepoTarget
	var marshaler = struct {
		embed
		OpenedAt *internal.DateTime `json:"opened_at,omitempty"`
	}{
		embed:    embed(*r),
		OpenedAt: internal.NewOptionalDateTime(r.OpenedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RepoTarget) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	repoTargetsDataFieldRecommendationID = big.NewInt(1 << 0)
	repoTargetsDataFieldItems            = big.NewInt(1 << 1)
)

type RepoTargetsData struct {
	RecommendationID string        `json:"recommendation_id" url:"recommendation_id"`
	Items            []*RepoTarget `json:"items" url:"items"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RepoTargetsData) GetRecommendationID() string {
	if r == nil {
		return ""
	}
	return r.RecommendationID
}

func (r *RepoTargetsData) GetItems() []*RepoTarget {
	if r == nil {
		return nil
	}
	return r.Items
}

func (r *RepoTargetsData) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RepoTargetsData) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRecommendationID sets the RecommendationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTargetsData) SetRecommendationID(recommendationID string) {
	r.RecommendationID = recommendationID
	r.require(repoTargetsDataFieldRecommendationID)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTargetsData) SetItems(items []*RepoTarget) {
	r.Items = items
	r.require(repoTargetsDataFieldItems)
}

func (r *RepoTargetsData) UnmarshalJSON(data []byte) error {
	type unmarshaler RepoTargetsData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RepoTargetsData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RepoTargetsData) MarshalJSON() ([]byte, error) {
	type embed RepoTargetsData
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RepoTargetsData) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	repoTargetsResponseFieldSuccess   = big.NewInt(1 << 0)
	repoTargetsResponseFieldTimestamp = big.NewInt(1 << 1)
	repoTargetsResponseFieldData      = big.NewInt(1 << 2)
)

type RepoTargetsResponse struct {
	Success   *bool            `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time       `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *RepoTargetsData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RepoTargetsResponse) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *RepoTargetsResponse) GetTimestamp() *time.Time {
	if r == nil {
		return nil
	}
	return r.Timestamp
}

func (r *RepoTargetsResponse) GetData() *RepoTargetsData {
	if r == nil {
		return nil
	}
	return r.Data
}

func (r *RepoTargetsResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RepoTargetsResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTargetsResponse) SetSuccess(success *bool) {
	r.Success = success
	r.require(repoTargetsResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTargetsResponse) SetTimestamp(timestamp *time.Time) {
	r.Timestamp = timestamp
	r.require(repoTargetsResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTargetsResponse) SetData(data *RepoTargetsData) {
	r.Data = data
	r.require(repoTargetsResponseFieldData)
}

func (r *RepoTargetsResponse) UnmarshalJSON(data []byte) error {
	type embed RepoTargetsResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RepoTargetsResponse(unmarshaler.embed)
	r.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RepoTargetsResponse) MarshalJSON() ([]byte, error) {
	type embed RepoTargetsResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*r),
		Timestamp: internal.NewOptionalDateTime(r.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RepoTargetsResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	srcRepoBindingSchemasGithubInstallationFieldInstallationID = big.NewInt(1 << 0)
	srcRepoBindingSchemasGithubInstallationFieldAccountLogin   = big.NewInt(1 << 1)
)

type SrcRepoBindingSchemasGithubInstallation struct {
	InstallationID int    `json:"installation_id" url:"installation_id"`
	AccountLogin   string `json:"account_login" url:"account_login"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SrcRepoBindingSchemasGithubInstallation) GetInstallationID() int {
	if s == nil {
		return 0
	}
	return s.InstallationID
}

func (s *SrcRepoBindingSchemasGithubInstallation) GetAccountLogin() string {
	if s == nil {
		return ""
	}
	return s.AccountLogin
}

func (s *SrcRepoBindingSchemasGithubInstallation) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SrcRepoBindingSchemasGithubInstallation) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetInstallationID sets the InstallationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SrcRepoBindingSchemasGithubInstallation) SetInstallationID(installationID int) {
	s.InstallationID = installationID
	s.require(srcRepoBindingSchemasGithubInstallationFieldInstallationID)
}

// SetAccountLogin sets the AccountLogin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SrcRepoBindingSchemasGithubInstallation) SetAccountLogin(accountLogin string) {
	s.AccountLogin = accountLogin
	s.require(srcRepoBindingSchemasGithubInstallationFieldAccountLogin)
}

func (s *SrcRepoBindingSchemasGithubInstallation) UnmarshalJSON(data []byte) error {
	type unmarshaler SrcRepoBindingSchemasGithubInstallation
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SrcRepoBindingSchemasGithubInstallation(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SrcRepoBindingSchemasGithubInstallation) MarshalJSON() ([]byte, error) {
	type embed SrcRepoBindingSchemasGithubInstallation
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SrcRepoBindingSchemasGithubInstallation) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	srcRepoBindingSchemasGithubInstallationsDataFieldItems = big.NewInt(1 << 0)
)

type SrcRepoBindingSchemasGithubInstallationsData struct {
	Items []*SrcRepoBindingSchemasGithubInstallation `json:"items" url:"items"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SrcRepoBindingSchemasGithubInstallationsData) GetItems() []*SrcRepoBindingSchemasGithubInstallation {
	if s == nil {
		return nil
	}
	return s.Items
}

func (s *SrcRepoBindingSchemasGithubInstallationsData) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SrcRepoBindingSchemasGithubInstallationsData) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SrcRepoBindingSchemasGithubInstallationsData) SetItems(items []*SrcRepoBindingSchemasGithubInstallation) {
	s.Items = items
	s.require(srcRepoBindingSchemasGithubInstallationsDataFieldItems)
}

func (s *SrcRepoBindingSchemasGithubInstallationsData) UnmarshalJSON(data []byte) error {
	type unmarshaler SrcRepoBindingSchemasGithubInstallationsData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SrcRepoBindingSchemasGithubInstallationsData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SrcRepoBindingSchemasGithubInstallationsData) MarshalJSON() ([]byte, error) {
	type embed SrcRepoBindingSchemasGithubInstallationsData
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SrcRepoBindingSchemasGithubInstallationsData) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	srcRepoBindingSchemasGithubInstallationsResponseFieldSuccess   = big.NewInt(1 << 0)
	srcRepoBindingSchemasGithubInstallationsResponseFieldTimestamp = big.NewInt(1 << 1)
	srcRepoBindingSchemasGithubInstallationsResponseFieldData      = big.NewInt(1 << 2)
)

type SrcRepoBindingSchemasGithubInstallationsResponse struct {
	Success   *bool                                         `json:"success,omitempty" url:"success,omitempty"`
	Timestamp *time.Time                                    `json:"timestamp,omitempty" url:"timestamp,omitempty"`
	Data      *SrcRepoBindingSchemasGithubInstallationsData `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SrcRepoBindingSchemasGithubInstallationsResponse) GetSuccess() *bool {
	if s == nil {
		return nil
	}
	return s.Success
}

func (s *SrcRepoBindingSchemasGithubInstallationsResponse) GetTimestamp() *time.Time {
	if s == nil {
		return nil
	}
	return s.Timestamp
}

func (s *SrcRepoBindingSchemasGithubInstallationsResponse) GetData() *SrcRepoBindingSchemasGithubInstallationsData {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *SrcRepoBindingSchemasGithubInstallationsResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SrcRepoBindingSchemasGithubInstallationsResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SrcRepoBindingSchemasGithubInstallationsResponse) SetSuccess(success *bool) {
	s.Success = success
	s.require(srcRepoBindingSchemasGithubInstallationsResponseFieldSuccess)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SrcRepoBindingSchemasGithubInstallationsResponse) SetTimestamp(timestamp *time.Time) {
	s.Timestamp = timestamp
	s.require(srcRepoBindingSchemasGithubInstallationsResponseFieldTimestamp)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SrcRepoBindingSchemasGithubInstallationsResponse) SetData(data *SrcRepoBindingSchemasGithubInstallationsData) {
	s.Data = data
	s.require(srcRepoBindingSchemasGithubInstallationsResponseFieldData)
}

func (s *SrcRepoBindingSchemasGithubInstallationsResponse) UnmarshalJSON(data []byte) error {
	type embed SrcRepoBindingSchemasGithubInstallationsResponse
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = SrcRepoBindingSchemasGithubInstallationsResponse(unmarshaler.embed)
	s.Timestamp = unmarshaler.Timestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SrcRepoBindingSchemasGithubInstallationsResponse) MarshalJSON() ([]byte, error) {
	type embed SrcRepoBindingSchemasGithubInstallationsResponse
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp,omitempty"`
	}{
		embed:     embed(*s),
		Timestamp: internal.NewOptionalDateTime(s.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SrcRepoBindingSchemasGithubInstallationsResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	unbindRepoAPIV1RepoBindingRecommendationsRecommendationIDTargetsDeleteRequestFieldRepoFullName = big.NewInt(1 << 0)
)

type UnbindRepoAPIV1RepoBindingRecommendationsRecommendationIDTargetsDeleteRequest struct {
	// Full name (owner/name) of the repository to unbind
	RepoFullName string `json:"-" url:"repo_full_name"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UnbindRepoAPIV1RepoBindingRecommendationsRecommendationIDTargetsDeleteRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetRepoFullName sets the RepoFullName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnbindRepoAPIV1RepoBindingRecommendationsRecommendationIDTargetsDeleteRequest) SetRepoFullName(repoFullName string) {
	u.RepoFullName = repoFullName
	u.require(unbindRepoAPIV1RepoBindingRecommendationsRecommendationIDTargetsDeleteRequestFieldRepoFullName)
}

var (
	repoTargetPatchRequestFieldInstallationID = big.NewInt(1 << 0)
	repoTargetPatchRequestFieldPrURL          = big.NewInt(1 << 1)
	repoTargetPatchRequestFieldPrNumber       = big.NewInt(1 << 2)
	repoTargetPatchRequestFieldPrStatus       = big.NewInt(1 << 3)
	repoTargetPatchRequestFieldOpenedAt       = big.NewInt(1 << 4)
	repoTargetPatchRequestFieldErrorMessage   = big.NewInt(1 << 5)
)

type RepoTargetPatchRequest struct {
	// GitHub App installation id, used to resolve the tenant. Falls back to the repository owner when omitted.
	InstallationID *int `json:"installation_id,omitempty" url:"-"`
	// Web URL of the pull request
	PrURL *string `json:"pr_url,omitempty" url:"-"`
	// Pull request number
	PrNumber *int `json:"pr_number,omitempty" url:"-"`
	// Lifecycle state of the pull request: 'open', 'merged', 'closed', or 'failed'
	PrStatus *string `json:"pr_status,omitempty" url:"-"`
	// ISO 8601 timestamp the pull request was opened
	OpenedAt *string `json:"opened_at,omitempty" url:"-"`
	// Why the pull request could not be opened
	ErrorMessage *string `json:"error_message,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RepoTargetPatchRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetInstallationID sets the InstallationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTargetPatchRequest) SetInstallationID(installationID *int) {
	r.InstallationID = installationID
	r.require(repoTargetPatchRequestFieldInstallationID)
}

// SetPrURL sets the PrURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTargetPatchRequest) SetPrURL(prURL *string) {
	r.PrURL = prURL
	r.require(repoTargetPatchRequestFieldPrURL)
}

// SetPrNumber sets the PrNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTargetPatchRequest) SetPrNumber(prNumber *int) {
	r.PrNumber = prNumber
	r.require(repoTargetPatchRequestFieldPrNumber)
}

// SetPrStatus sets the PrStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTargetPatchRequest) SetPrStatus(prStatus *string) {
	r.PrStatus = prStatus
	r.require(repoTargetPatchRequestFieldPrStatus)
}

// SetOpenedAt sets the OpenedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTargetPatchRequest) SetOpenedAt(openedAt *string) {
	r.OpenedAt = openedAt
	r.require(repoTargetPatchRequestFieldOpenedAt)
}

// SetErrorMessage sets the ErrorMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RepoTargetPatchRequest) SetErrorMessage(errorMessage *string) {
	r.ErrorMessage = errorMessage
	r.require(repoTargetPatchRequestFieldErrorMessage)
}

func (r *RepoTargetPatchRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RepoTargetPatchRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RepoTargetPatchRequest(body)
	return nil
}

func (r *RepoTargetPatchRequest) MarshalJSON() ([]byte, error) {
	type embed RepoTargetPatchRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}
