// Code generated by Fern. DO NOT EDIT.

package auth

import (
	context "context"
	levelfour "github.com/LevelFourAI/levelfour-go"
	core "github.com/LevelFourAI/levelfour-go/core"
	internal "github.com/LevelFourAI/levelfour-go/internal"
	option "github.com/LevelFourAI/levelfour-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) GetWhoami(
	ctx context.Context,
	opts ...option.RequestOption,
) (*levelfour.WhoamiResponse, error) {
	response, err := c.WithRawResponse.GetWhoami(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
