// Code generated by Fern. DO NOT EDIT.

package apikeys

import (
	context "context"
	levelfour "github.com/LevelFourAI/levelfour-go"
	core "github.com/LevelFourAI/levelfour-go/core"
	internal "github.com/LevelFourAI/levelfour-go/internal"
	option "github.com/LevelFourAI/levelfour-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) List(
	ctx context.Context,
	opts ...option.RequestOption,
) (*levelfour.ListAPIKeysResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Create(
	ctx context.Context,
	request *levelfour.CreateAPIKeyRequest,
	opts ...option.RequestOption,
) (*levelfour.CreateAPIKeyResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Revoke(
	ctx context.Context,
	// API key UUID
	keyID string,
	opts ...option.RequestOption,
) (*levelfour.RevokeAPIKeyResponse, error) {
	response, err := c.WithRawResponse.Revoke(
		ctx,
		keyID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Rotate(
	ctx context.Context,
	// API key UUID to rotate
	keyID string,
	opts ...option.RequestOption,
) (*levelfour.CreateAPIKeyResponse, error) {
	response, err := c.WithRawResponse.Rotate(
		ctx,
		keyID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
