// Code generated by Fern. DO NOT EDIT.

package providers

import (
	context "context"
	levelfour "github.com/LevelFourAI/levelfour-go"
	core "github.com/LevelFourAI/levelfour-go/core"
	internal "github.com/LevelFourAI/levelfour-go/internal"
	option "github.com/LevelFourAI/levelfour-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) List(
	ctx context.Context,
	opts ...option.RequestOption,
) (*levelfour.ProvidersListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the top users by realized (captured) savings for a provider, ranked descending (max 3)
func (c *Client) GetProviderTopSavers(
	ctx context.Context,
	providerID string,
	opts ...option.RequestOption,
) (*levelfour.TopSaversResponse, error) {
	response, err := c.WithRawResponse.GetProviderTopSavers(
		ctx,
		providerID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns spend per invoice month split by cost type (regular, tax, adjustment, rounding). Google Cloud only; other providers return no months.
func (c *Client) GetProviderInvoices(
	ctx context.Context,
	providerID string,
	request *levelfour.GetProviderInvoicesAPIV1ProvidersProviderIDCostsInvoicesGetRequest,
	opts ...option.RequestOption,
) (*levelfour.InvoicesResponse, error) {
	response, err := c.WithRawResponse.GetProviderInvoices(
		ctx,
		providerID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
