// Code generated by Fern. DO NOT EDIT.

package commitments

import (
	context "context"
	levelfour "github.com/LevelFourAI/levelfour-go"
	core "github.com/LevelFourAI/levelfour-go/core"
	internal "github.com/LevelFourAI/levelfour-go/internal"
	option "github.com/LevelFourAI/levelfour-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// ESR strip and aggregate RI/SP metrics for the requested provider (AWS real, GCP/Azure return zeros).
func (c *Client) GetOverview(
	ctx context.Context,
	request *levelfour.GetOverviewAPIV1CommitmentsOverviewGetRequest,
	opts ...option.RequestOption,
) (*levelfour.CommitmentsOverviewResponse, error) {
	response, err := c.WithRawResponse.GetOverview(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Paginated coverage breakdown by commitment row.
func (c *Client) GetCoverage(
	ctx context.Context,
	request *levelfour.GetCoverageAPIV1CommitmentsCoverageGetRequest,
	opts ...option.RequestOption,
) (*levelfour.CommitmentsCoverageResponse, error) {
	response, err := c.WithRawResponse.GetCoverage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetCoverageFilterOptions(
	ctx context.Context,
	request *levelfour.GetCoverageFilterOptionsAPIV1CommitmentsCoverageFilterOptionsGetRequest,
	opts ...option.RequestOption,
) (*levelfour.CoverageFilterOptionsResponse, error) {
	response, err := c.WithRawResponse.GetCoverageFilterOptions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ListCommitments(
	ctx context.Context,
	request *levelfour.ListCommitmentsAPIV1CommitmentsGetRequest,
	opts ...option.RequestOption,
) (*levelfour.CommitmentListResponse, error) {
	response, err := c.WithRawResponse.ListCommitments(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetDetail(
	ctx context.Context,
	commitmentID string,
	opts ...option.RequestOption,
) (*levelfour.CommitmentDetailResponse, error) {
	response, err := c.WithRawResponse.GetDetail(
		ctx,
		commitmentID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a service x instrument matrix of RI and SP utilization, coverage, unused, and uncovered values. One row per service that has at least one commitment.
func (c *Client) GetByService(
	ctx context.Context,
	request *levelfour.GetByServiceAPIV1CommitmentsByServiceGetRequest,
	opts ...option.RequestOption,
) (*levelfour.CommitmentsByServiceResponse, error) {
	response, err := c.WithRawResponse.GetByService(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetRecommendations(
	ctx context.Context,
	request *levelfour.GetRecommendationsAPIV1CommitmentsRecommendationsGetRequest,
	opts ...option.RequestOption,
) (*levelfour.CommitmentRecommendationsResponse, error) {
	response, err := c.WithRawResponse.GetRecommendations(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// One row per commitment across every connected account, resolving the account that holds it against the accounts that consume it, with the expiry instant, the utilization trend, and what a renewal protects kept separate from what right-sizing would save.
func (c *Client) GetPortfolio(
	ctx context.Context,
	request *levelfour.GetPortfolioAPIV1CommitmentsPortfolioGetRequest,
	opts ...option.RequestOption,
) (*levelfour.CommitmentPortfolioResponse, error) {
	response, err := c.WithRawResponse.GetPortfolio(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// What the same usage would have cost at public on-demand rates against what it actually cost, for the organization and for each account that consumed the benefit. The rate is split into the part a negotiated agreement earns and the part commitments earn, because the public on-demand price sits above both and an account owning no commitment at all would otherwise report a healthy rate.
func (c *Client) GetEsr(
	ctx context.Context,
	request *levelfour.GetEsrAPIV1CommitmentsEsrGetRequest,
	opts ...option.RequestOption,
) (*levelfour.EsrResponse, error) {
	response, err := c.WithRawResponse.GetEsr(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// On-demand spend no commitment covers, split by platform and volatility. Carries the hourly floor as well as the average, because sizing against the average of a volatile base commits more than the base can sustain.
func (c *Client) GetUncovered(
	ctx context.Context,
	opts ...option.RequestOption,
) (*levelfour.UncoveredResponse, error) {
	response, err := c.WithRawResponse.GetUncovered(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// What to repurchase and when. States the instant to buy after rather than a date, because a replacement bills from the moment it is bought, and lists the pending changes that must land first so their capacity is not reserved for another term.
func (c *Client) GetRenewalPlan(
	ctx context.Context,
	commitmentID string,
	opts ...option.RequestOption,
) (*levelfour.RenewalPlanResponse, error) {
	response, err := c.WithRawResponse.GetRenewalPlan(
		ctx,
		commitmentID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Commitment relationships that behave like a commitment on the bill but appear in no provider commitment view, with the contracted floor separated from the metered leg that bills on top.
func (c *Client) GetContracts(
	ctx context.Context,
	opts ...option.RequestOption,
) (*levelfour.ContractsResponse, error) {
	response, err := c.WithRawResponse.GetContracts(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
