// Code generated by Fern. DO NOT EDIT.

package health

import (
	context "context"
	levelfour "github.com/LevelFourAI/levelfour-go"
	core "github.com/LevelFourAI/levelfour-go/core"
	internal "github.com/LevelFourAI/levelfour-go/internal"
	option "github.com/LevelFourAI/levelfour-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Readiness probe — verifies the platform DB pool is reachable.
func (c *Client) HealthReady(
	ctx context.Context,
	opts ...option.RequestOption,
) (*levelfour.HealthCheckResponse, error) {
	response, err := c.WithRawResponse.HealthReady(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Readiness probe (HEAD).
func (c *Client) HealthReadyHead(
	ctx context.Context,
	opts ...option.RequestOption,
) (any, error) {
	response, err := c.WithRawResponse.HealthReadyHead(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Header, nil
}
