// Code generated by Fern. DO NOT EDIT.

package ceseed

import (
	context "context"
	levelfour "github.com/LevelFourAI/levelfour-go"
	core "github.com/LevelFourAI/levelfour-go/core"
	internal "github.com/LevelFourAI/levelfour-go/internal"
	option "github.com/LevelFourAI/levelfour-go/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) TriggerCeSeed(
	ctx context.Context,
	request *levelfour.CeSeedTriggerRequest,
	opts ...option.RequestOption,
) (*core.Response[*levelfour.CeSeedTriggerResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"",
	)
	endpointURL := baseURL + "/api/v1/ce-seed/trigger"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("x-service-key", request.ServiceKey)
	headers.Add("Content-Type", "application/json")
	var response *levelfour.CeSeedTriggerResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(levelfour.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*levelfour.CeSeedTriggerResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
