// Code generated by Fern. DO NOT EDIT.

package costs

import (
	context "context"
	levelfour "github.com/LevelFourAI/levelfour-go"
	core "github.com/LevelFourAI/levelfour-go/core"
	internal "github.com/LevelFourAI/levelfour-go/internal"
	option "github.com/LevelFourAI/levelfour-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Returns spending summary: overall costs, forecast, savings, and provider breakdown
func (c *Client) GetSummary(
	ctx context.Context,
	opts ...option.RequestOption,
) (*levelfour.SpendingSummaryResponse, error) {
	response, err := c.WithRawResponse.GetSummary(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns services ranked by largest percent growth between current and previous period.
func (c *Client) GetTopGrowing(
	ctx context.Context,
	request *levelfour.GetTopGrowingAPIV1CostsTopGrowingGetRequest,
	opts ...option.RequestOption,
) (*levelfour.TopGrowingResponse, error) {
	response, err := c.WithRawResponse.GetTopGrowing(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the distinct tag keys present in the tenant's per-tag cost data so the dashboard can offer them as choices.
func (c *Client) GetTagKeys(
	ctx context.Context,
	request *levelfour.GetTagKeysAPIV1CostsByTagKeysGetRequest,
	opts ...option.RequestOption,
) (*levelfour.TagKeysResponse, error) {
	response, err := c.WithRawResponse.GetTagKeys(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns spend grouped by tag_value for a given tag_key (e.g., team, tribe, squad, cost-center). Includes a per-team category breakdown.
func (c *Client) GetCostByTag(
	ctx context.Context,
	request *levelfour.GetCostByTagAPIV1CostsByTagGetRequest,
	opts ...option.RequestOption,
) (*levelfour.TeamCostResponse, error) {
	response, err := c.WithRawResponse.GetCostByTag(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns showback coverage for a tag key: total, tagged, untagged, coverage percentage, and a per-value breakdown.
func (c *Client) GetAllocation(
	ctx context.Context,
	request *levelfour.GetAllocationAPIV1CostsAllocationGetRequest,
	opts ...option.RequestOption,
) (*levelfour.AllocationResponse, error) {
	response, err := c.WithRawResponse.GetAllocation(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns spend, billable quantity, unit, and derived cost per unit grouped by usage type.
func (c *Client) GetUsage(
	ctx context.Context,
	request *levelfour.GetUsageAPIV1CostsUsageGetRequest,
	opts ...option.RequestOption,
) (*levelfour.UsageResponse, error) {
	response, err := c.WithRawResponse.GetUsage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns forecasted spend value, confidence bounds, and a 60-point sparkline (past 30 days actual + next 30 days forecast).
func (c *Client) GetForecast(
	ctx context.Context,
	request *levelfour.GetForecastAPIV1CostsForecastGetRequest,
	opts ...option.RequestOption,
) (*levelfour.ForecastResponse, error) {
	response, err := c.WithRawResponse.GetForecast(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns cost breakdown in different formats: table (paginated), chart (aggregated), csv (export), raw (all records)
func (c *Client) List(
	ctx context.Context,
	request *levelfour.ListCostsRequest,
	opts ...option.RequestOption,
) (*levelfour.ListCostsResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns daily spending aggregated per day for the given date range
func (c *Client) GetDailyCosts(
	ctx context.Context,
	request *levelfour.GetDailyCostsCostsRequest,
	opts ...option.RequestOption,
) (*levelfour.DailySpendingBreakdownResponse, error) {
	response, err := c.WithRawResponse.GetDailyCosts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns monthly spending aggregated per month
func (c *Client) GetMonthlyCosts(
	ctx context.Context,
	opts ...option.RequestOption,
) (*levelfour.MonthlySpendingResponse, error) {
	response, err := c.WithRawResponse.GetMonthlyCosts(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns spending summary for a specific cloud provider
func (c *Client) GetProviderSummary(
	ctx context.Context,
	providerID string,
	opts ...option.RequestOption,
) (*levelfour.ProviderSpendingSummaryResponse, error) {
	response, err := c.WithRawResponse.GetProviderSummary(
		ctx,
		providerID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns available values for every filter dimension. Dimensions cross-constrain each other (AWS Cost Explorer behavior); each dimension excludes its own selections when computing its option list.
func (c *Client) GetProviderFilters(
	ctx context.Context,
	providerID string,
	request *levelfour.GetProviderFiltersCostsRequest,
	opts ...option.RequestOption,
) (*levelfour.ProviderFilterOptionsResponse, error) {
	response, err := c.WithRawResponse.GetProviderFilters(
		ctx,
		providerID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns service breakdown in different formats: table (paginated), chart (aggregated), csv (export), raw (all records)
func (c *Client) ListByProvider(
	ctx context.Context,
	providerID string,
	request *levelfour.ListByProviderCostsRequest,
	opts ...option.RequestOption,
) (*levelfour.ListByProviderCostsResponse, error) {
	response, err := c.WithRawResponse.ListByProvider(
		ctx,
		providerID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns spending timeline for a specific provider
func (c *Client) GetProviderTimeline(
	ctx context.Context,
	providerID string,
	request *levelfour.GetProviderTimelineCostsRequest,
	opts ...option.RequestOption,
) (*levelfour.ProviderTimelineResponse, error) {
	response, err := c.WithRawResponse.GetProviderTimeline(
		ctx,
		providerID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
